/*==============================================================
Object Name    : FILE_FORMAT / STAGE SETUP
Purpose        : Create file formats for CSV ingestion and
                 reference the external stage for data loading.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-01
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create CSV file format for customer and order data ingestion
---------------------------------------------------------

-- Create CSV file format for data ingestion
-- Purpose: Defines parsing rules for CSV files including header skip, field delimiter, and error tolerance
CREATE FILE FORMAT IF NOT EXISTS IDEA_2_DB.PUBLIC.CSV_FILE_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    NULL_IF = ('', 'NULL', 'null', 'N/A')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;