/*==============================================================
Object Name    : CUSTOMER / ORDER / ORDERSUMMARY / CUSTOMERAGGREGATESPEND
Purpose        : Create all target tables required for the
                 customer-order data pipeline including SCD2
                 and aggregation tables.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-01
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create CUSTOMER staging/landing table
---------------------------------------------------------

-- Create CUSTOMER table for raw customer data
-- Purpose: Landing table for customer CSV data with 4 columns: CUSTID, NAME, EMAILID, REGION
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMER (
    CUSTID      VARCHAR(100),
    NAME        VARCHAR(500),
    EMAILID     VARCHAR(500),
    REGION      VARCHAR(200)
);

---------------------------------------------------------
-- SECTION 2
-- Purpose: Create ORDER staging/landing table
---------------------------------------------------------

-- Create ORDER table for raw order data
-- Purpose: Landing table for order CSV data with 9 columns: ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC."order" (
    ORDERID         VARCHAR(100),
    CUSTID          VARCHAR(100),
    ITEMNAME        VARCHAR(500),
    PRICEPERUNIT    NUMBER(18,2),
    QTY             NUMBER(18,0),
    ORDER_DATE      DATE,
    STARTDATE       DATE,
    ENDDATE         DATE,
    ISACTIVE        VARCHAR(10)
);

---------------------------------------------------------
-- SECTION 3
-- Purpose: Create ORDERSUMMARY table with SCD Type 2 columns
---------------------------------------------------------

-- Create ORDERSUMMARY table with SCD2 tracking columns
-- Purpose: Stores joined customer-order data with SCD Type 2 fields (IS_CURRENT, EFFECTIVE_FROM, EFFECTIVE_TO) for historical tracking
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.ORDERSUMMARY (
    ORDERSUMMARY_SK     NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CUSTID              VARCHAR(100),
    NAME                VARCHAR(500),
    EMAILID             VARCHAR(500),
    REGION              VARCHAR(200),
    ORDERID             VARCHAR(100),
    ITEMNAME            VARCHAR(500),
    PRICEPERUNIT        NUMBER(18,2),
    QTY                 NUMBER(18,0),
    TOTALAMOUNT         NUMBER(18,2),
    ORDER_DATE          DATE,
    STARTDATE           DATE,
    ENDDATE             DATE,
    ISACTIVE            VARCHAR(10),
    IS_CURRENT          BOOLEAN DEFAULT TRUE,
    EFFECTIVE_FROM      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO        TIMESTAMP_NTZ DEFAULT '9999-12-31 00:00:00'::TIMESTAMP_NTZ,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

---------------------------------------------------------
-- SECTION 4
-- Purpose: Create CUSTOMERAGGREGATESPEND table for aggregated results
---------------------------------------------------------

-- Create CUSTOMERAGGREGATESPEND table
-- Purpose: Stores aggregated total spend per customer per date for reporting and analytics
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND (
    NAME            VARCHAR(500),
    TOTALAMOUNT     NUMBER(18,2),
    ORDER_DATE      DATE,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);