/*==============================================================
Object Name    : COPY INTO CUSTOMER / ORDER
Purpose        : Ingest customer and order CSV data from
                 Snowflake stage into landing tables.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-01
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Log pipeline start for data ingestion
---------------------------------------------------------

-- Log start of data ingestion step
-- Purpose: Record pipeline step initiation for observability
INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PIPELINE_NAME, STEP_NAME, STEP_STATUS, MESSAGE)
VALUES ('CUSTOMER_ORDER_PIPELINE', 'DATA_INGESTION_START', 'STARTED', 'Beginning data load from stage into landing tables');

---------------------------------------------------------
-- SECTION 2
-- Purpose: Truncate landing tables before fresh load
---------------------------------------------------------

-- Truncate CUSTOMER table before reload
-- Purpose: Ensure clean state for full refresh load pattern
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC.CUSTOMER;

-- Truncate ORDER table before reload
-- Purpose: Ensure clean state for full refresh load pattern
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC."order";

---------------------------------------------------------
-- SECTION 3
-- Purpose: Load customer data from stage into CUSTOMER table
---------------------------------------------------------

-- Copy customer data from stage into CUSTOMER table
-- Purpose: Ingest customer CSV file (CUSTID, NAME, EMAILID, REGION) from external stage with error tolerance
COPY INTO IDEA_2_DB.PUBLIC.CUSTOMER (CUSTID, NAME, EMAILID, REGION)
FROM @gen_ai_poc_snowflakecoe.sdlc_wizard.sdlc_wizard_stage/customerdata
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    NULL_IF = ('', 'NULL', 'null', 'N/A')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = CONTINUE;

---------------------------------------------------------
-- SECTION 4
-- Purpose: Load order data from stage into ORDER table
---------------------------------------------------------

-- Copy order data from stage into ORDER table
-- Purpose: Ingest order CSV file (ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE) from external stage with error tolerance
COPY INTO IDEA_2_DB.PUBLIC."order" (ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE)
FROM @gen_ai_poc_snowflakecoe.sdlc_wizard.sdlc_wizard_stage/orderdata
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    NULL_IF = ('', 'NULL', 'null', 'N/A')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = CONTINUE;

---------------------------------------------------------
-- SECTION 5
-- Purpose: Log completion of data ingestion
---------------------------------------------------------

-- Log completion of data ingestion step
-- Purpose: Record successful completion of data load for audit trail
INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PIPELINE_NAME, STEP_NAME, STEP_STATUS, MESSAGE)
VALUES ('CUSTOMER_ORDER_PIPELINE', 'DATA_INGESTION_COMPLETE', 'COMPLETED', 'Customer and order data loaded from stage into landing tables');