/*==============================================================
Object Name    : DATA CLEANSING - CUSTOMER / ORDER
Purpose        : Remove null key records and duplicate records
                 from CUSTOMER and ORDER landing tables to
                 ensure data quality before downstream processing.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-01
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Log start of data cleansing
---------------------------------------------------------

-- Log start of data cleansing step
-- Purpose: Record pipeline step initiation for observability
INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PIPELINE_NAME, STEP_NAME, STEP_STATUS, MESSAGE)
VALUES ('CUSTOMER_ORDER_PIPELINE', 'DATA_CLEANSING_START', 'STARTED', 'Beginning null and duplicate removal from landing tables');

---------------------------------------------------------
-- SECTION 2
-- Purpose: Remove null CUSTID records from CUSTOMER table
---------------------------------------------------------

-- Delete records with NULL CUSTID from CUSTOMER table
-- Purpose: Ensure referential integrity by removing records without a valid customer identifier
DELETE FROM IDEA_2_DB.PUBLIC.CUSTOMER
WHERE CUSTID IS NULL;

---------------------------------------------------------
-- SECTION 3
-- Purpose: Remove duplicate CUSTID records from CUSTOMER table using Snowflake-compatible dedup
---------------------------------------------------------

-- Create a deduplicated version of CUSTOMER table
-- Purpose: Identify and retain only one record per CUSTID using ROW_NUMBER window function, removing all true duplicates
CREATE OR REPLACE TEMPORARY TABLE IDEA_2_DB.PUBLIC.CUSTOMER_DEDUP AS
SELECT
    CUSTID,
    NAME,
    EMAILID,
    REGION
FROM IDEA_2_DB.PUBLIC.CUSTOMER
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTID ORDER BY NAME) = 1;

-- Truncate CUSTOMER table before reloading deduplicated data
-- Purpose: Clear existing data to replace with clean deduplicated records
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC.CUSTOMER;

-- Reload deduplicated customer data
-- Purpose: Insert only unique CUSTID records back into the CUSTOMER table
INSERT INTO IDEA_2_DB.PUBLIC.CUSTOMER (CUSTID, NAME, EMAILID, REGION)
SELECT CUSTID, NAME, EMAILID, REGION
FROM IDEA_2_DB.PUBLIC.CUSTOMER_DEDUP;

---------------------------------------------------------
-- SECTION 4
-- Purpose: Remove null ORDERID records from ORDER table
---------------------------------------------------------

-- Delete records with NULL ORDERID from ORDER table
-- Purpose: Ensure referential integrity by removing records without a valid order identifier
DELETE FROM IDEA_2_DB.PUBLIC."order"
WHERE ORDERID IS NULL;

---------------------------------------------------------
-- SECTION 5
-- Purpose: Remove duplicate ORDERID records from ORDER table using Snowflake-compatible dedup
---------------------------------------------------------

-- Create a deduplicated version of ORDER table
-- Purpose: Identify and retain only one record per ORDERID using ROW_NUMBER window function
CREATE OR REPLACE TEMPORARY TABLE IDEA_2_DB.PUBLIC.ORDER_DEDUP AS
SELECT
    ORDERID,
    CUSTID,
    ITEMNAME,
    PRICEPERUNIT,
    QTY,
    ORDER_DATE,
    STARTDATE,
    ENDDATE,
    ISACTIVE
FROM IDEA_2_DB.PUBLIC."order"
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDERID ORDER BY CUSTID) = 1;

-- Truncate ORDER table before reloading deduplicated data
-- Purpose: Clear existing data to replace with clean deduplicated records
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC."order";

-- Reload deduplicated order data
-- Purpose: Insert only unique ORDERID records back into the ORDER table
INSERT INTO IDEA_2_DB.PUBLIC."order" (ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE)
SELECT ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE
FROM IDEA_2_DB.PUBLIC.ORDER_DEDUP;

---------------------------------------------------------
-- SECTION 6
-- Purpose: Log completion of data cleansing
---------------------------------------------------------

-- Log completion of data cleansing step
-- Purpose: Record successful completion of null/duplicate removal for audit trail
INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PIPELINE_NAME, STEP_NAME, STEP_STATUS, MESSAGE)
VALUES ('CUSTOMER_ORDER_PIPELINE', 'DATA_CLEANSING_COMPLETE', 'COMPLETED', 'Null and duplicate records removed from CUSTOMER and ORDER tables');