/*==============================================================
Object Name    : ORDERSUMMARY - Initial Load
Purpose        : Join CUSTOMER and ORDER tables and load the
                 combined data into the ORDERSUMMARY table with
                 computed TOTALAMOUNT and SCD2 tracking columns.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-01
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Log start of ordersummary load
---------------------------------------------------------

-- Log start of ordersummary load step
-- Purpose: Record pipeline step initiation for observability
INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PIPELINE_NAME, STEP_NAME, STEP_STATUS, MESSAGE)
VALUES ('CUSTOMER_ORDER_PIPELINE', 'ORDERSUMMARY_LOAD_START', 'STARTED', 'Beginning join of CUSTOMER and ORDER into ORDERSUMMARY');

---------------------------------------------------------
-- SECTION 2
-- Purpose: Create staging table with joined customer-order data
---------------------------------------------------------

-- Create temporary staging table with joined data
-- Purpose: Join CUSTOMER and ORDER on CUSTID, compute TOTALAMOUNT (PRICEPERUNIT * QTY), and prepare for MERGE into ORDERSUMMARY
CREATE OR REPLACE TEMPORARY TABLE IDEA_2_DB.PUBLIC.ORDERSUMMARY_STG AS
SELECT
    C.CUSTID,
    C.NAME,
    C.EMAILID,
    C.REGION,
    O.ORDERID,
    O.ITEMNAME,
    O.PRICEPERUNIT,
    O.QTY,
    (O.PRICEPERUNIT * O.QTY) AS TOTALAMOUNT,
    O.ORDER_DATE,
    O.STARTDATE,
    O.ENDDATE,
    O.ISACTIVE
FROM IDEA_2_DB.PUBLIC.CUSTOMER C
INNER JOIN IDEA_2_DB.PUBLIC."order" O
    ON C.CUSTID = O.CUSTID;

---------------------------------------------------------
-- SECTION 3
-- Purpose: Insert joined data into ORDERSUMMARY table
---------------------------------------------------------

-- Insert joined customer-order data into ORDERSUMMARY
-- Purpose: Load the initial set of joined records with SCD2 defaults (IS_CURRENT=TRUE, EFFECTIVE_TO=9999-12-31)
INSERT INTO IDEA_2_DB.PUBLIC.ORDERSUMMARY (
    CUSTID,
    NAME,
    EMAILID,
    REGION,
    ORDERID,
    ITEMNAME,
    PRICEPERUNIT,
    QTY,
    TOTALAMOUNT,
    ORDER_DATE,
    STARTDATE,
    ENDDATE,
    ISACTIVE,
    IS_CURRENT,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    CREATED_AT,
    UPDATED_AT
)
SELECT
    CUSTID,
    NAME,
    EMAILID,
    REGION,
    ORDERID,
    ITEMNAME,
    PRICEPERUNIT,
    QTY,
    TOTALAMOUNT,
    ORDER_DATE,
    STARTDATE,
    ENDDATE,
    ISACTIVE,
    TRUE AS IS_CURRENT,
    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,
    '9999-12-31 00:00:00'::TIMESTAMP_NTZ AS EFFECTIVE_TO,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY_STG;

---------------------------------------------------------
-- SECTION 4
-- Purpose: Log completion of ordersummary load
---------------------------------------------------------

-- Log completion of ordersummary load step
-- Purpose: Record successful completion of ordersummary population for audit trail
INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PIPELINE_NAME, STEP_NAME, STEP_STATUS, MESSAGE)
VALUES ('CUSTOMER_ORDER_PIPELINE', 'ORDERSUMMARY_LOAD_COMPLETE', 'COMPLETED', 'Joined customer-order data loaded into ORDERSUMMARY table');