/*==============================================================
Object Name    : ORDERSUMMARY - SCD Type 2 MERGE
Purpose        : Implement SCD Type 2 logic on ORDERSUMMARY
                 table to track historical changes in customer
                 and order attributes. Expire old records and
                 insert new versions when changes are detected.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-01
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Log start of SCD2 processing
---------------------------------------------------------

-- Log start of SCD2 merge step
-- Purpose: Record pipeline step initiation for observability
INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PIPELINE_NAME, STEP_NAME, STEP_STATUS, MESSAGE)
VALUES ('CUSTOMER_ORDER_PIPELINE', 'SCD2_MERGE_START', 'STARTED', 'Beginning SCD Type 2 merge on ORDERSUMMARY');

---------------------------------------------------------
-- SECTION 2
-- Purpose: Prepare incoming data for SCD2 comparison
---------------------------------------------------------

-- Create staging table with current source data for SCD2 comparison
-- Purpose: Build the latest view of customer-order data to compare against existing ORDERSUMMARY records
CREATE OR REPLACE TEMPORARY TABLE IDEA_2_DB.PUBLIC.ORDERSUMMARY_SCD2_STG AS
SELECT
    C.CUSTID,
    C.NAME,
    C.EMAILID,
    C.REGION,
    O.ORDERID,
    O.ITEMNAME,
    O.PRICEPERUNIT,
    O.QTY,
    (O.PRICEPERUNIT * O.QTY) AS TOTALAMOUNT,
    O.ORDER_DATE,
    O.STARTDATE,
    O.ENDDATE,
    O.ISACTIVE
FROM IDEA_2_DB.PUBLIC.CUSTOMER C
INNER JOIN IDEA_2_DB.PUBLIC."order" O
    ON C.CUSTID = O.CUSTID;

---------------------------------------------------------
-- SECTION 3
-- Purpose: Expire existing current records that have changed (SCD2 close-out)
---------------------------------------------------------

-- Update existing current records to expire them when source data has changed
-- Purpose: Set IS_CURRENT=FALSE and EFFECTIVE_TO=CURRENT_TIMESTAMP for records where customer or order attributes have changed
UPDATE IDEA_2_DB.PUBLIC.ORDERSUMMARY TGT
SET
    IS_CURRENT = FALSE,
    EFFECTIVE_TO = CURRENT_TIMESTAMP(),
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE TGT.IS_CURRENT = TRUE
AND EXISTS (
    SELECT 1
    FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY_SCD2_STG SRC
    WHERE SRC.CUSTID = TGT.CUSTID
      AND SRC.ORDERID = TGT.ORDERID
      AND (
          SRC.NAME        != TGT.NAME
       OR SRC.EMAILID     != TGT.EMAILID
       OR SRC.REGION      != TGT.REGION
       OR SRC.ITEMNAME    != TGT.ITEMNAME
       OR SRC.PRICEPERUNIT != TGT.PRICEPERUNIT
       OR SRC.QTY         != TGT.QTY
       OR SRC.ISACTIVE    != TGT.ISACTIVE
       OR SRC.STARTDATE   != TGT.STARTDATE
       OR SRC.ENDDATE     != TGT.ENDDATE
      )
);

---------------------------------------------------------
-- SECTION 4
-- Purpose: Insert new version records for changed data (SCD2 new rows)
---------------------------------------------------------

-- Insert new current version records for changed data
-- Purpose: Create new SCD2 rows with IS_CURRENT=TRUE for records that were expired in the previous step
INSERT INTO IDEA_2_DB.PUBLIC.ORDERSUMMARY (
    CUSTID,
    NAME,
    EMAILID,
    REGION,
    ORDERID,
    ITEMNAME,
    PRICEPERUNIT,
    QTY,
    TOTALAMOUNT,
    ORDER_DATE,
    STARTDATE,
    ENDDATE,
    ISACTIVE,
    IS_CURRENT,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    CREATED_AT,
    UPDATED_AT
)
SELECT
    SRC.CUSTID,
    SRC.NAME,
    SRC.EMAILID,
    SRC.REGION,
    SRC.ORDERID,
    SRC.ITEMNAME,
    SRC.PRICEPERUNIT,
    SRC.QTY,
    SRC.TOTALAMOUNT,
    SRC.ORDER_DATE,
    SRC.STARTDATE,
    SRC.ENDDATE,
    SRC.ISACTIVE,
    TRUE AS IS_CURRENT,
    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,
    '9999-12-31 00:00:00'::TIMESTAMP_NTZ AS EFFECTIVE_TO,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY_SCD2_STG SRC
WHERE EXISTS (
    SELECT 1
    FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY TGT
    WHERE TGT.CUSTID = SRC.CUSTID
      AND TGT.ORDERID = SRC.ORDERID
      AND TGT.IS_CURRENT = FALSE
      AND TGT.EFFECTIVE_TO >= DATEADD('MINUTE', -5, CURRENT_TIMESTAMP())
);

---------------------------------------------------------
-- SECTION 5
-- Purpose: Insert brand new records that do not exist in ORDERSUMMARY
---------------------------------------------------------

-- Insert completely new records not yet in ORDERSUMMARY
-- Purpose: Add new customer-order combinations that have no prior history in the SCD2 table
INSERT INTO IDEA_2_DB.PUBLIC.ORDERSUMMARY (
    CUSTID,
    NAME,
    EMAILID,
    REGION,
    ORDERID,
    ITEMNAME,
    PRICEPERUNIT,
    QTY,
    TOTALAMOUNT,
    ORDER_DATE,
    STARTDATE,
    ENDDATE,
    ISACTIVE,
    IS_CURRENT,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    CREATED_AT,
    UPDATED_AT
)
SELECT
    SRC.CUSTID,
    SRC.NAME,
    SRC.EMAILID,
    SRC.REGION,
    SRC.ORDERID,
    SRC.ITEMNAME,
    SRC.PRICEPERUNIT,
    SRC.QTY,
    SRC.TOTALAMOUNT,
    SRC.ORDER_DATE,
    SRC.STARTDATE,
    SRC.ENDDATE,
    SRC.ISACTIVE,
    TRUE AS IS_CURRENT,
    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,
    '9999-12-31 00:00:00'::TIMESTAMP_NTZ AS EFFECTIVE_TO,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY_SCD2_STG SRC
WHERE NOT EXISTS (
    SELECT 1
    FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY TGT
    WHERE TGT.CUSTID = SRC.CUSTID
      AND TGT.ORDERID = SRC.ORDERID
);

---------------------------------------------------------
-- SECTION 6
-- Purpose: Update ISACTIVE flag based on source ISACTIVE status
---------------------------------------------------------

-- Update ORDERSUMMARY ISACTIVE flag for inactive customers
-- Purpose: Mark records as inactive in ORDERSUMMARY when the source ORDER table indicates ISACTIVE = FALSE
UPDATE IDEA_2_DB.PUBLIC.ORDERSUMMARY
SET
    ISACTIVE = 'FALSE',
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE IS_CURRENT = TRUE
AND CUSTID IN (
    SELECT DISTINCT CUSTID
    FROM IDEA_2_DB.PUBLIC."order"
    WHERE UPPER(ISACTIVE) = 'FALSE'
);

---------------------------------------------------------
-- SECTION 7
-- Purpose: Log completion of SCD2 processing
---------------------------------------------------------

-- Log completion of SCD2 merge step
-- Purpose: Record successful completion of SCD2 processing for audit trail
INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PIPELINE_NAME, STEP_NAME, STEP_STATUS, MESSAGE)
VALUES ('CUSTOMER_ORDER_PIPELINE', 'SCD2_MERGE_COMPLETE', 'COMPLETED', 'SCD Type 2 merge on ORDERSUMMARY completed successfully');