/*==============================================================
Object Name    : CUSTOMERAGGREGATESPEND - Aggregation & Publish
Purpose        : Aggregate TOTALAMOUNT from ORDERSUMMARY by
                 NAME and ORDER_DATE, then load results into
                 CUSTOMERAGGREGATESPEND reporting table.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-01
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Log start of aggregation step
---------------------------------------------------------

-- Log start of aggregation step
-- Purpose: Record pipeline step initiation for observability
INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PIPELINE_NAME, STEP_NAME, STEP_STATUS, MESSAGE)
VALUES ('CUSTOMER_ORDER_PIPELINE', 'AGGREGATION_START', 'STARTED', 'Beginning aggregation of TOTALAMOUNT from ORDERSUMMARY');

---------------------------------------------------------
-- SECTION 2
-- Purpose: Truncate target aggregation table before fresh load
---------------------------------------------------------

-- Truncate CUSTOMERAGGREGATESPEND before reload
-- Purpose: Ensure clean state for full refresh of aggregated data to avoid double-counting
TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND;

---------------------------------------------------------
-- SECTION 3
-- Purpose: Aggregate and load data into CUSTOMERAGGREGATESPEND
---------------------------------------------------------

-- Insert aggregated spend data into CUSTOMERAGGREGATESPEND
-- Purpose: Compute SUM of TOTALAMOUNT grouped by NAME and ORDER_DATE from current ORDERSUMMARY records for reporting
INSERT INTO IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND (NAME, TOTALAMOUNT, ORDER_DATE, CREATED_AT)
SELECT
    NAME,
    SUM(TOTALAMOUNT) AS TOTALAMOUNT,
    ORDER_DATE,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY
WHERE IS_CURRENT = TRUE
GROUP BY NAME, ORDER_DATE
ORDER BY NAME, ORDER_DATE;

---------------------------------------------------------
-- SECTION 4
-- Purpose: Log completion of aggregation and publish
---------------------------------------------------------

-- Log completion of aggregation step
-- Purpose: Record successful completion of aggregation and publish for audit trail
INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PIPELINE_NAME, STEP_NAME, STEP_STATUS, MESSAGE)
VALUES ('CUSTOMER_ORDER_PIPELINE', 'AGGREGATION_COMPLETE', 'COMPLETED', 'Aggregated data loaded into CUSTOMERAGGREGATESPEND table');