/*==============================================================
Object Name    : PIPELINE_LOG / PIPELINE_ERROR_LOG
Purpose        : Create logging and error handling tables to
                 support pipeline observability and debugging.
Generated By   : SDLC_DEVELOPER
Generated Date : 2024-01-01
==============================================================*/

---------------------------------------------------------
-- SECTION 1
-- Purpose: Create pipeline logging table
---------------------------------------------------------

-- Create pipeline execution log table
-- Purpose: Tracks each step of the data pipeline with timestamps, row counts, and status
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.PIPELINE_LOG (
    LOG_ID          NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PIPELINE_NAME   VARCHAR(200),
    STEP_NAME       VARCHAR(500),
    STEP_STATUS     VARCHAR(50),
    ROW_COUNT       NUMBER DEFAULT 0,
    MESSAGE         VARCHAR(4000),
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

---------------------------------------------------------
-- SECTION 2
-- Purpose: Create pipeline error log table
---------------------------------------------------------

-- Create pipeline error log table
-- Purpose: Captures detailed error information including error codes and stack traces
CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.PIPELINE_ERROR_LOG (
    ERROR_LOG_ID    NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PIPELINE_NAME   VARCHAR(200),
    STEP_NAME       VARCHAR(500),
    ERROR_CODE      VARCHAR(100),
    ERROR_MESSAGE   VARCHAR(4000),
    ERROR_STATE     VARCHAR(100),
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);