/*=========================================================
Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
  WAREHOUSE = W_CAPG_APAC_IND_DEMO_IDEA_REFACTOR_SOL_XS
  SCHEDULE = 'USING CRON 0 02 * * * UTC'
AS
  CALL GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1();