/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : ETL reconciliation log DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE W_CAPG_APAC_IND_DEMO_IDEA_REFACTOR_SOL_XS;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS ETL_RECONCILIATION_LOG (
    RUN_ID                  VARCHAR(100)        NOT NULL,
    RUN_TIMESTAMP           TIMESTAMP_NTZ       DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_COUNT            NUMBER(12),
    FILTERED_COUNT          NUMBER(12),
    DEDUP_COUNT             NUMBER(12),
    INSERT_COUNT            NUMBER(12),
    UPDATE_COUNT            NUMBER(12),
    SOFT_DELETE_COUNT       NUMBER(12),
    TARGET_COUNT_PRE        NUMBER(12),
    TARGET_COUNT_POST       NUMBER(12),
    WATERMARK_FROM          TIMESTAMP_NTZ,
    WATERMARK_TO            TIMESTAMP_NTZ,
    STATUS                  VARCHAR(20),
    ERROR_MESSAGE           VARCHAR(4000),
    LOAD_TYPE               VARCHAR(20),
    EXECUTION_SECONDS       NUMBER(10,2),
    PIPELINE_NAME           VARCHAR(200)
);

-- SECTION 2: Constraints
ALTER TABLE ETL_RECONCILIATION_LOG
    ADD CONSTRAINT IF NOT EXISTS PK_RECON_RUN_ID PRIMARY KEY (RUN_ID);

-- SECTION 3: Notes
-- One row per SP execution. RUN_ID = pipeline name + YYYYMMDDHHMI timestamp.
-- WATERMARK_FROM/TO track incremental window applied during the run.
-- STATUS values: RUNNING | SUCCESS | FAILED.