/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_SOURCE
Purpose     : Source table DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS AEROSPACE_PARTS_SOURCE (
    PART_NUMBER             VARCHAR(50)         NOT NULL,
    MANUFACTURER            VARCHAR(100),
    WEIGHT_KG               NUMBER(10,4),
    UNIT_PRICE_USD          NUMBER(18,2),
    CERTIFICATION_STATUS    VARCHAR(50),
    LEAD_TIME_DAYS          NUMBER(6,0),
    LIFECYCLE_STATUS        VARCHAR(50),
    INSTALLATION_DATE       DATE,
    UPDATED_AT              TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
ALTER TABLE AEROSPACE_PARTS_SOURCE
    ADD CONSTRAINT IF NOT EXISTS UQ_SRC_PART_NUMBER UNIQUE (PART_NUMBER);

-- SECTION 3: Notes
-- Business Key: PART_NUMBER
-- Incremental load driven by UPDATED_AT
-- LIFECYCLE_STATUS used for exclusion filter (End of Life + INSTALLATION_DATE > 3 yrs)