/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_TARGET
Purpose     : Target table DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE W_CAPG_APAC_IND_DEMO_IDEA_REFACTOR_SOL_XS;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS AEROSPACE_PARTS_TARGET (
    PART_NUMBER             VARCHAR(50)         NOT NULL,
    MANUFACTURER            VARCHAR(100),
    WEIGHT_KG               NUMBER(10,4),
    UNIT_PRICE_USD          NUMBER(14,2),
    CERTIFICATION_STATUS    VARCHAR(50),
    LEAD_TIME_DAYS          NUMBER(6),
    INSTALLATION_DATE       DATE,
    PART_DESCRIPTION        VARCHAR(500),
    CATEGORY                VARCHAR(100),
    SUPPLIER_ID             VARCHAR(50),
    STOCK_QUANTITY          NUMBER(12),
    UNIT_OF_MEASURE         VARCHAR(20),
    COUNTRY_OF_ORIGIN       VARCHAR(100),
    RISK_SCORE              VARCHAR(20),
    RECORD_STATUS           VARCHAR(30)         DEFAULT 'Active',
    UPDATED_AT              TIMESTAMP_NTZ,
    CREATED_AT              TIMESTAMP_NTZ       DEFAULT CURRENT_TIMESTAMP(),
    ETL_LOAD_TS             TIMESTAMP_NTZ       DEFAULT CURRENT_TIMESTAMP(),
    ETL_RUN_ID              VARCHAR(100)
);

-- SECTION 2: Constraints
ALTER TABLE AEROSPACE_PARTS_TARGET
    ADD CONSTRAINT IF NOT EXISTS PK_TGT_PART_NUMBER PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- SCD Type 1 target. PART_NUMBER is the unique business key.
-- RISK_SCORE derived: High/Medium/Low per BRD rules at load time.
-- RECORD_STATUS = 'Decommissioned' for soft-deleted records absent from source.
-- ETL_RUN_ID links to ETL_RECONCILIATION_LOG.RUN_ID.