/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_SOURCE
Purpose     : Source table DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE W_CAPG_APAC_IND_DEMO_IDEA_REFACTOR_SOL_XS;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS AEROSPACE_PARTS_SOURCE (
    PART_NUMBER             VARCHAR(50)         NOT NULL,
    MANUFACTURER            VARCHAR(100),
    WEIGHT_KG               NUMBER(10,4),
    UNIT_PRICE_USD          NUMBER(14,2),
    CERTIFICATION_STATUS    VARCHAR(50),
    LEAD_TIME_DAYS          NUMBER(6),
    INSTALLATION_DATE       DATE,
    UPDATED_AT              TIMESTAMP_NTZ,
    PART_DESCRIPTION        VARCHAR(500),
    CATEGORY                VARCHAR(100),
    SUPPLIER_ID             VARCHAR(50),
    STOCK_QUANTITY          NUMBER(12),
    UNIT_OF_MEASURE         VARCHAR(20),
    COUNTRY_OF_ORIGIN       VARCHAR(100),
    CREATED_AT              TIMESTAMP_NTZ       DEFAULT CURRENT_TIMESTAMP()
);

-- SECTION 2: Constraints
ALTER TABLE AEROSPACE_PARTS_SOURCE
    ADD CONSTRAINT IF NOT EXISTS UQ_SRC_PART_NUMBER UNIQUE (PART_NUMBER);

-- SECTION 3: Notes
-- Source staging table for aerospace parts inventory.
-- UPDATED_AT drives incremental watermark logic in SP.
-- INSTALLATION_DATE used for End-of-Life exclusion (older than 3 years).