/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : ETL reconciliation log DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS ETL_RECONCILIATION_LOG (
    RUN_ID                  VARCHAR(100)        NOT NULL,
    RUN_TIMESTAMP           TIMESTAMP_NTZ       DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_COUNT            NUMBER(18,0),
    INSERTED_COUNT          NUMBER(18,0),
    UPDATED_COUNT           NUMBER(18,0),
    DELETED_COUNT           NUMBER(18,0),
    SOFT_DELETED_COUNT      NUMBER(18,0),
    EXCLUDED_COUNT          NUMBER(18,0),
    WATERMARK_FROM          TIMESTAMP_NTZ,
    WATERMARK_TO            TIMESTAMP_NTZ,
    STATUS                  VARCHAR(20),
    ERROR_MESSAGE           VARCHAR(4000)
);

-- SECTION 2: Constraints
ALTER TABLE ETL_RECONCILIATION_LOG
    ADD CONSTRAINT IF NOT EXISTS PK_RECON_RUN_ID PRIMARY KEY (RUN_ID);

-- SECTION 3: Notes
-- One row per pipeline execution
-- SOFT_DELETED_COUNT tracks records set to Decommissioned (RULE-007)
-- STATUS values: SUCCESS | FAILED | PARTIAL