/*=========================================================
Object Name : SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1(
    P_LOAD_TYPE   VARCHAR DEFAULT 'INCREMENTAL',
    P_ETL_RUN_ID  VARCHAR DEFAULT NULL
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
-- SECTION 1: Variables

    -- ----------------------------------------------------------------
    -- Runtime identifiers
    -- ----------------------------------------------------------------
    V_RUN_ID            VARCHAR;
    V_PIPELINE_NAME     VARCHAR  DEFAULT 'SP_LOAD_AEROSPACE_PARTS_SCD1';
    V_LOAD_TYPE         VARCHAR;
    V_START_TS          TIMESTAMP_NTZ;
    V_END_TS            TIMESTAMP_NTZ;
    V_EXECUTION_SECONDS NUMBER(18,3);

    -- ----------------------------------------------------------------
    -- Watermarks
    -- ----------------------------------------------------------------
    V_WATERMARK_-- SECTION 2: Source Processing
FROM    TIMESTAMP_NTZ;
    V_WATERMARK_TO      TIMESTAMP_NTZ;

    -- ----------------------------------------------------------------
    -- Reconciliation counters
    -- ----------------------------------------------------------------
    V_SOURCE_COUNT          NUMBER DEFAULT 0;
    V_DEDUP_COUNT           NUMBER DEFAULT 0;
    V_FILTERED_COUNT        NUMBER DEFAULT 0;
    V_TARGET_COUNT_PRE      NUMBER DEFAULT 0;
    V_TARGET_COUNT_POST     NUMBER DEFAULT 0;
    V_INSERT_COUNT          NUMBER DEFAULT 0;
    V_UPDATE_COUNT          NUMBER DEFAULT 0;
    V_SOFT_DELETE_COUNT     NUMBER DEFAULT 0;

    -- ----------------------------------------------------------------
    -- Status / error
    -- ----------------------------------------------------------------
    V_STATUS        VARCHAR  DEFAULT 'SUCCESS';
    V_ERROR_MESSAGE VARCHAR  DEFAULT NULL;

    -- ----------------------------------------------------------------
    -- Result payload
    -- ----------------------------------------------------------------
    V_RESULT        VARCHAR;

BEGIN
    -- ============================================================
    -- 0. Initialise
    -- ============================================================
    V_START_TS  := CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ;
    V_LOAD_TYPE := UPPER(-- SECTION 3: Data Validation
COALESCE(P_LOAD_TYPE, 'INCREMENTAL'));
    V_RUN_ID    := COALESCE(
                       P_ETL_RUN_ID,
                       'RUN_' || TO_VARCHAR(V_START_TS, 'YYYYMMDD_HH24MISS')
                   );

    -- ============================================================
    -- 1. Pre-load target row count
    -- ============================================================
    SELECT COUNT(1)
    INTO   V_TARGET_COUNT_PRE
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;

    -- ============================================================
    -- 2. Determine watermarks
    -- ============================================================
    IF (V_LOAD_TYPE = 'INCREMENTAL') THEN

        -- Low watermark = last successful watermark_to for this pipeline
        SELECT COALESCE(MAX(WATERMARK_TO), '1900-01-01'::TIMESTAMP_NTZ)
        INTO   V_WATERMARK_FROM
        FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
        WHERE  PIPELINE_NAME = V_PIPELINE_NAME
          AND  STATUS        = 'SUCCESS';

        -- High watermark = latest UPDATED_AT in source
        SELECT COALESCE(MAX(UPDATED_AT), V_WATERMARK_FROM)
        INTO   V_WATERMARK_TO
        FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE;

    ELSE
        -- FULL load — span entire source history
        SELECT COALESCE(MIN(UPDATED_AT), '1900-01-01'::TIMESTAMP_NTZ),
               COALESCE(MAX(UPDATED_AT), CURRENT_TIMESTAMP()::TIMESTAMP_NTZ)
        INTO   V_WATERMARK_FROM,
               V_WATERMARK_TO
        FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE;

    END IF;

    -- ============================================================
    -- 3. Stage: raw source count
    -- ============================================================
    SELECT COUNT(1)
    INTO   V_SOURCE_COUNT
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    WHERE  (V_LOAD_TYPE = 'FULL')
        OR (UPDATED_AT > V_WATERMARK_FROM AND UPDATED_AT <= V_WATERMARK_TO);

    -- ============================================================
    -- 4. Build deduplicated + transformed staging CTE and MERGE
    -- ============================================================
    -- 4a. Count post-dedup (1 row per PART_NUMBER, latest UPDATED_AT)
    SELECT COUNT(1)
    INTO   V_DEDUP_COUNT
    FROM (
        SELECT PART_NUMBER,
               ROW_NUMBER() OVER (
                   PARTITION BY PART_NUMBER
                   ORDER BY     UPDATED_AT DESC, CREATED_AT DESC
               ) AS RN
        FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE  (V_LOAD_TYPE = 'FULL')
            OR (UPDATED_AT > V_WATERMARK_FROM AND UPDATED_AT <= V_WATERMARK_TO)
    ) AS DEDUP_CTE
    WHERE RN = 1;

    -- 4b. Count filtered-out records (invalid / excluded rows)
    --     Business rule: exclude rows where PART_NUMBER IS NULL
    --     or UNIT_PRICE_USD < 0 or WEIGHT_KG < 0
    SELECT COUNT(1)
    INTO   V_FILTERED_COUNT
    FROM (
        SELECT PART_NUMBER,
               UNIT_PRICE_USD,
               WEIGHT_KG,
               ROW_NUMBER() OVER (
                   PARTITION BY PART_NUMBER
                   ORDER BY     UPDATED_AT DESC, CREATED_AT DESC
               ) AS RN
        FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE  (V_LOAD_TYPE = 'FULL')
            OR (UPDATED_AT > V_WATERMARK_FROM AND UPDATED_AT <= V_WATERMARK_TO)
    ) AS FLTR
    WHERE RN = 1
      AND (
              PART_NUMBER   IS NULL
           OR UNIT_PRICE_USD < 0
           OR WEIGHT_KG      < 0
          );

    -- ============================================================
    -- 5. SCD Type 1 MERGE
    -- ============================================================
    -- SECTION 4: Merge Logic
MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS TGT
    USING (
        /* --------------------------------------------------------
           Deduplicate source: keep latest row per PART_NUMBER.
           Apply all transformation / business rules here.
        -------------------------------------------------------- */
        SELECT
            -- Business key
            SRC.PART_NUMBER,

            -- Transformed columns
            UPPER(TRIM(SRC.MANUFACTURER))                          AS MANUFACTURER,

            CASE
                WHEN SRC.WEIGHT_KG IS NULL OR SRC.WEIGHT_KG <= 0
                    THEN NULL
                ELSE SRC.WEIGHT_KG
            END                                                    AS WEIGHT_KG,

            CASE
                WHEN UPPER(TRIM(SRC.UNIT_OF_MEASURE)) IN (
                         'KG','LB','EACH','SET','BOX','METER','LITER','CM','MM','INCH'
                     )
                    THEN UPPER(TRIM(SRC.UNIT_OF_MEASURE))
                ELSE 'EACH'
            END                                                    AS UNIT_OF_MEASURE,

            -- RISK_SCORE derivation
            CASE
                WHEN SRC.UNIT_PRICE_USD > 90000                            THEN 'High Risk'
                WHEN SRC.CERTIFICATION_STATUS = 'Pending'
                  OR SRC.LEAD_TIME_DAYS       > 90                         THEN 'Medium Risk'
                ELSE                                                             'Low Risk'
            END                                                    AS RISK_SCORE,

            -- RECORD_STATUS derivation
            CASE
                WHEN SRC.STOCK_QUANTITY = 0                                THEN 'Out of Stock'
                WHEN SRC.INSTALLATION_DATE < CURRENT_DATE()                THEN 'Installed'
                WHEN SRC.CERTIFICATION_STATUS = 'Expired'                  THEN 'Non-Compliant'
                ELSE                                                             'Active'
            END                                                    AS RECORD_STATUS,

            -- Pass-through columns
            SRC.CATEGORY,
            SRC.CERTIFICATION_STATUS,
            SRC.COUNTRY_OF_ORIGIN,
            SRC.CREATED_AT,
            SRC.INSTALLATION_DATE,
            SRC.LEAD_TIME_DAYS,
            SRC.PART_DESCRIPTION,
            SRC.STOCK_QUANTITY,
            SRC.SUPPLIER_ID,
            SRC.UNIT_PRICE_USD,
            SRC.UPDATED_AT,

            -- ETL metadata
            V_START_TS  AS ETL_LOAD_TS,
            V_RUN_ID    AS ETL_RUN_ID

        FROM (
            SELECT *,
                   ROW_NUMBER() OVER (
                       PARTITION BY PART_NUMBER
                       ORDER BY     UPDATED_AT DESC, CREATED_AT DESC
                   ) AS _RN
            FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
            WHERE  (V_LOAD_TYPE = 'FULL')
                OR (UPDATED_AT > V_WATERMARK_FROM AND UPDATED_AT <= V_WATERMARK_TO)
        ) AS SRC
        WHERE SRC._RN = 1
          -- Filter: exclude invalid records
          AND SRC.PART_NUMBER    IS NOT NULL
          AND SRC.UNIT_PRICE_USD >= 0
          AND SRC.WEIGHT_KG      >= 0

    ) AS STAGED
    ON  TGT.PART_NUMBER = STAGED.PART_NUMBER

    -- ---- MATCH: SCD1 overwrite changed rows ----------------------
    WHEN MATCHED
         AND (
               TGT.MANUFACTURER         <> STAGED.MANUFACTURER
            OR TGT.PART_DESCRIPTION     <> STAGED.PART_DESCRIPTION
            OR TGT.CATEGORY             <> STAGED.CATEGORY
            OR TGT.CERTIFICATION_STATUS <> STAGED.CERTIFICATION_STATUS
            OR TGT.COUNTRY_OF_ORIGIN    <> STAGED.COUNTRY_OF_ORIGIN
            OR TGT.INSTALLATION_DATE    <> STAGED.INSTALLATION_DATE
            OR TGT.LEAD_TIME_DAYS       <> STAGED.LEAD_TIME_DAYS
            OR TGT.STOCK_QUANTITY       <> STAGED.STOCK_QUANTITY
            OR TGT.SUPPLIER_ID          <> STAGED.SUPPLIER_ID
            OR TGT.UNIT_OF_MEASURE      <> STAGED.UNIT_OF_MEASURE
            OR TGT.UNIT_PRICE_USD       <> STAGED.UNIT_PRICE_USD
            OR TGT.WEIGHT_KG            <> STAGED.WEIGHT_KG
            OR ZEROIFNULL(TGT.WEIGHT_KG)     <> ZEROIFNULL(STAGED.WEIGHT_KG)
            OR TGT.RISK_SCORE           <> STAGED.RISK_SCORE
            OR TGT.RECORD_STATUS        <> STAGED.RECORD_STATUS
         )
    THEN UPDATE SET
        TGT.MANUFACTURER         = STAGED.MANUFACTURER,
        TGT.PART_DESCRIPTION     = STAGED.PART_DESCRIPTION,
        TGT.CATEGORY             = STAGED.CATEGORY,
        TGT.CERTIFICATION_STATUS = STAGED.CERTIFICATION_STATUS,
        TGT.COUNTRY_OF_ORIGIN    = STAGED.COUNTRY_OF_ORIGIN,
        TGT.INSTALLATION_DATE    = STAGED.INSTALLATION_DATE,
        TGT.LEAD_TIME_DAYS       = STAGED.LEAD_TIME_DAYS,
        TGT.STOCK_QUANTITY       = STAGED.STOCK_QUANTITY,
        TGT.SUPPLIER_ID          = STAGED.SUPPLIER_ID,
        TGT.UNIT_OF_MEASURE      = STAGED.UNIT_OF_MEASURE,
        TGT.UNIT_PRICE_USD       = STAGED.UNIT_PRICE_USD,
        TGT.WEIGHT_KG            = STAGED.WEIGHT_KG,
        TGT.RISK_SCORE           = STAGED.RISK_SCORE,
        TGT.RECORD_STATUS        = STAGED.RECORD_STATUS,
        TGT.UPDATED_AT           = STAGED.UPDATED_AT,
        TGT.ETL_LOAD_TS          = STAGED.ETL_LOAD_TS,
        TGT.ETL_RUN_ID           = STAGED.ETL_RUN_ID

    -- ---- NO MATCH: insert new row --------------------------------
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER,
        MANUFACTURER,
        PART_DESCRIPTION,
        CATEGORY,
        CERTIFICATION_STATUS,
        COUNTRY_OF_ORIGIN,
        CREATED_AT,
        INSTALLATION_DATE,
        LEAD_TIME_DAYS,
        STOCK_QUANTITY,
        SUPPLIER_ID,
        UNIT_OF_MEASURE,
        UNIT_PRICE_USD,
        WEIGHT_KG,
        RISK_SCORE,
        RECORD_STATUS,
        UPDATED_AT,
        ETL_LOAD_TS,
        ETL_RUN_ID
    )
    VALUES (
        STAGED.PART_NUMBER,
        STAGED.MANUFACTURER,
        STAGED.PART_DESCRIPTION,
        STAGED.CATEGORY,
        STAGED.CERTIFICATION_STATUS,
        STAGED.COUNTRY_OF_ORIGIN,
        STAGED.CREATED_AT,
        STAGED.INSTALLATION_DATE,
        STAGED.LEAD_TIME_DAYS,
        STAGED.STOCK_QUANTITY,
        STAGED.SUPPLIER_ID,
        STAGED.UNIT_OF_MEASURE,
        STAGED.UNIT_PRICE_USD,
        STAGED.WEIGHT_KG,
        STAGED.RISK_SCORE,
        STAGED.RECORD_STATUS,
        STAGED.UPDATED_AT,
        STAGED.ETL_LOAD_TS,
        STAGED.ETL_RUN_ID
    );

    -- ============================================================
    -- 6. Capture DML row counts from MERGE
    -- ============================================================
    V_INSERT_COUNT := (SELECT "number of rows inserted" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
    V_UPDATE_COUNT := (SELECT "number of rows updated"  FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

    -- Soft-delete: mark target rows whose PART_NUMBER no longer
    -- exists in source as 'Inactive' (applies to FULL load only)
    IF (V_LOAD_TYPE = 'FULL') THEN

        UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS TGT
        SET    TGT.RECORD_STATUS = 'Inactive',
               TGT.ETL_LOAD_TS  = V_START_TS,
               TGT.ETL_RUN_ID   = V_RUN_ID