/*=========================================================
Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_AEROSPACE_PARTS_ETL()
RETURNS VARCHAR
LANGUAGE SQL
WAREHOUSE = SNOWFLAKE_LEARNING_WH
AS
$$
-- SECTION 1: Variables

    -- Watermark variables
    v_watermark_-- SECTION 2: Source Processing
from        TIMESTAMP_NTZ;
    v_watermark_to          TIMESTAMP_NTZ;

    -- Counters
    v_source_count          INTEGER DEFAULT 0;
    v_inserted_count        INTEGER DEFAULT 0;
    v_updated_count         INTEGER DEFAULT 0;
    v_deleted_count         INTEGER DEFAULT 0;
    v_soft_deleted_count    INTEGER DEFAULT 0;
    v_excluded_count        INTEGER DEFAULT 0;

    -- Run metadata
    v_run_id                VARCHAR;
    v_run_timestamp         TIMESTAMP_NTZ;
    v_status                VARCHAR DEFAULT 'SUCCESS';
    v_error_message         VARCHAR DEFAULT NULL;

    -- Result
    v_result                VARCHAR;

BEGIN
    -- -------------------------------------------------------------------------
    -- 1. Initialize run metadata
    -- -------------------------------------------------------------------------
    v_run_id        := GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_AEROSPACE_PARTS_ETL::VARCHAR
                       || '_' || TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDD_HH24MISS');
    v_run_id        := UUID_STRING();
    v_run_timestamp := CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ;

    -- -------------------------------------------------------------------------
    -- 2. Derive watermark boundaries
    --    WATERMARK_FROM = MAX(UPDATED_AT) from last successful run in log
    --    WATERMARK_TO   = current UTC timestamp
    -- -------------------------------------------------------------------------
    SELECT -- SECTION 3: Data Validation
COALESCE(MAX(WATERMARK_TO), '1900-01-01 00:00:00'::TIMESTAMP_NTZ)
      INTO v_watermark_from
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
     WHERE STATUS = 'SUCCESS';

    v_watermark_to := v_run_timestamp;

    -- -------------------------------------------------------------------------
    -- 3. Stage deduplicated incremental source records into a temp table
    --    Deduplication: retain latest record per PART_NUMBER by UPDATED_AT
    --    Transformation: MANUFACTURER -> UPPERCASE
    --                    WEIGHT_KG    -> rounded to 2 decimal places
    --                    RISK_SCORE   -> derived: LEAD_TIME_DAYS * UNIT_PRICE_USD / 1000
    --    Exclusion: records where UNIT_PRICE_USD <= 0 or PART_NUMBER IS NULL
    -- -------------------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_STAGED AS
    WITH ranked AS (
        SELECT
            PART_NUMBER,
            UPPER(MANUFACTURER)                                          AS MANUFACTURER,
            ROUND(WEIGHT_KG, 2)                                         AS WEIGHT_KG,
            UNIT_PRICE_USD,
            LEAD_TIME_DAYS,
            CERTIFICATION_STATUS,
            LIFECYCLE_STATUS,
            INSTALLATION_DATE,
            UPDATED_AT,
            ROUND((LEAD_TIME_DAYS * UNIT_PRICE_USD) / 1000.0, 4)        AS RISK_SCORE,
            ROW_NUMBER() OVER (
                PARTITION BY PART_NUMBER
                ORDER BY UPDATED_AT DESC
            )                                                            AS RN
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE UPDATED_AT  >  v_watermark_from
          AND UPDATED_AT  <= v_watermark_to
          AND PART_NUMBER IS NOT NULL
          AND UNIT_PRICE_USD > 0
    )
    SELECT
        PART_NUMBER,
        MANUFACTURER,
        WEIGHT_KG,
        UNIT_PRICE_USD,
        LEAD_TIME_DAYS,
        CERTIFICATION_STATUS,
        LIFECYCLE_STATUS,
        INSTALLATION_DATE,
        UPDATED_AT,
        RISK_SCORE
    FROM ranked
    WHERE RN = 1;

    -- -------------------------------------------------------------------------
    -- 4. Count source (qualified) records
    -- -------------------------------------------------------------------------
    SELECT COUNT(*)
      INTO v_source_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_STAGED;

    -- -------------------------------------------------------------------------
    -- 5. Count excluded records (NULL PART_NUMBER or non-positive UNIT_PRICE_USD
    --    within the incremental window)
    -- -------------------------------------------------------------------------
    SELECT COUNT(*)
      INTO v_excluded_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
     WHERE UPDATED_AT  >  v_watermark_from
       AND UPDATED_AT  <= v_watermark_to
       AND (PART_NUMBER IS NULL OR UNIT_PRICE_USD <= 0);

    -- -------------------------------------------------------------------------
    -- 6. SCD Type 1 -- SECTION 4: Merge Logic
MERGE into AEROSPACE_PARTS_TARGET
    --    Business key: PART_NUMBER
    -- -------------------------------------------------------------------------
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET  AS TGT
    USING GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TMP_AEROSPACE_STAGED          AS SRC
       ON TGT.PART_NUMBER = SRC.PART_NUMBER

    -- MATCHED: update all non-key columns (SCD Type 1 overwrite)
    WHEN MATCHED THEN UPDATE SET
        TGT.MANUFACTURER          = SRC.MANUFACTURER,
        TGT.WEIGHT_KG             = SRC.WEIGHT_KG,
        TGT.UNIT_PRICE_USD        = SRC.UNIT_PRICE_USD,
        TGT.LEAD_TIME_DAYS        = SRC.LEAD_TIME_DAYS,
        TGT.CERTIFICATION_STATUS  = SRC.CERTIFICATION_STATUS,
        TGT.LIFECYCLE_STATUS      = SRC.LIFECYCLE_STATUS,
        TGT.INSTALLATION_DATE     = SRC.INSTALLATION_DATE,
        TGT.UPDATED_AT            = SRC.UPDATED_AT,
        TGT.RISK_SCORE            = SRC.RISK_SCORE,
        TGT.DW_LAST_UPDATE_TIMESTAMP = v_run_timestamp

    -- NOT MATCHED: insert new record
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER,
        MANUFACTURER,
        WEIGHT_KG,
        UNIT_PRICE_USD,
        LEAD_TIME_DAYS,
        CERTIFICATION_STATUS,
        LIFECYCLE_STATUS,
        INSTALLATION_DATE,
        UPDATED_AT,
        RISK_SCORE,
        DW_INSERT_TIMESTAMP,
        DW_LAST_UPDATE_TIMESTAMP
    ) VALUES (
        SRC.PART_NUMBER,
        SRC.MANUFACTURER,
        SRC.WEIGHT_KG,
        SRC.UNIT_PRICE_USD,
        SRC.LEAD_TIME_DAYS,
        SRC.CERTIFICATION_STATUS,
        SRC.LIFECYCLE_STATUS,
        SRC.INSTALLATION_DATE,
        SRC.UPDATED_AT,
        SRC.RISK_SCORE,
        v_run_timestamp,
        v_run_timestamp
    );

    -- -------------------------------------------------------------------------
    -- 7. Capture MERGE row counts via RESULT_SCAN
    -- -------------------------------------------------------------------------
    SELECT
        SUM(CASE WHEN "number of rows inserted" > 0 THEN "number of rows inserted" ELSE 0 END),
        SUM(CASE WHEN "number of rows updated"  > 0 THEN "number of rows updated"  ELSE 0 END)
      INTO v_inserted_count, v_updated_count
      FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

    -- -------------------------------------------------------------------------
    -- 8. Soft delete: mark target records no longer present in full source
    --    as LIFECYCLE_STATUS = 'Decommissioned'
    --    Only process when a full-load watermark is not restricting scope.
    --    Strategy: any PART_NUMBER in TARGET that does NOT exist anywhere in
    --    SOURCE (not just the incremental window) is considered removed.
    -- -------------------------------------------------------------------------
    UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS TGT
       SET TGT.LIFECYCLE_STATUS          = 'Decommissioned',
           TGT.DW_LAST_UPDATE_TIMESTAMP  = v_run_timestamp
     WHERE TGT.LIFECYCLE_STATUS <> 'Decommissioned'
       AND NOT EXISTS (
               SELECT 1
                 FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE AS SRC
                WHERE SRC.PART_NUMBER = TGT.PART_NUMBER
           );

    -- Capture soft-delete count
    SELECT COUNT(*)
      INTO v_soft_deleted_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
     WHERE LIFECYCLE_STATUS = 'Decommissioned'
       AND DW_LAST_UPDATE_TIMESTAMP = v_run_timestamp;

    -- -------------------------------------------------------------------------
    -- 9. Hard-delete counter (not applicable for SCD Type 1 / soft-delete
    --    strategy; set to 0)
    -- -------------------------------------------------------------------------
    v_deleted_count := 0;

    -- -------------------------------------------------------------------------
    -- 10. Write reconciliation log (only columns that exist in DDL)
    -- -------------------------------------------------------------------------
    -- SECTION 5: Reconciliation
INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        RUN_ID,
        RUN_TIMESTAMP,
        STATUS,
        SOURCE_COUNT,
        INSERTED_COUNT,
        UPDATED_COUNT,
        DELETED_COUNT,
        SOFT_DELETED_COUNT,
        EXCLUDED_COUNT,
        WATERMARK_FROM,
        WATERMARK_TO,
        ERROR_MESSAGE
    ) VALUES (
        v_run_id,
        v_run_timestamp,
        v_status,
        v_source_count,
        v_inserted_count,
        v_updated_count,
        v_deleted_count,
        v_soft_deleted_count,
        v_excluded_count,
        v_watermark_from,
        v_watermark_to,
        v_error_message
    );

    -- -------------------------------------------------------------------------
    -- 11. Build and return success result
    -- -------------------------------------------------------------------------
    v_result := OBJECT_CONSTRUCT(
        'status',             v_status,
        'run_id',             v_run_id,
        'run_timestamp',      TO_VARCHAR(v_run_timestamp),
        'watermark_from',     TO_VARCHAR(v_watermark_from),
        'watermark_to',       TO_VARCHAR(v_watermark_to),
        'source_count',       v_source_count,
        'inserted_count',     v_inserted_count,
        'updated_count',      v_updated_count,
        'deleted_count',      v_deleted_count,
        'soft_deleted_count', v_soft_deleted_count,
        'excluded_count',     v_excluded_count
    )::VARCHAR;

    RETURN v_result;

-- SECTION 6: Error Handling
EXCEPTION
    WHEN OTHER THEN
        -- Log failure record
        INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
            RUN_ID,
            RUN_TIMESTAMP,
            STATUS,
            SOURCE_COUNT,
            INSERTED_COUNT,
            UPDATED_COUNT,
            DELETED_COUNT,
            SOFT_DELETED_COUNT,
            EXCLUDED_COUNT,
            WATERMARK_FROM,
            WATERMARK_TO,
            ERROR_MESSAGE
        ) VALUES (
            v_run_id,
            v_run_timestamp,
            'FAILED',
            v_source_count,
            v_inserted_count,
            v_updated_count,
            v_deleted_count,
            v_soft_deleted_count,
            v_excluded_count,
            v_watermark_from,
            v_watermark_to,
            SQLERRM
        );

        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;

END;
$$;