/*==============================================================
 File Name        : AEROSPACE_PARTS_PIPELINE_TASK.sql
 Object Name      : AEROSPACE_PARTS_PIPELINE_TASK
 Project          : SCRUM-150
 Purpose          : Scheduled task — daily at 03:00 UTC for AEROSPACE_PARTS_PIPELINE
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-10-05
 Work Item        : SCRUM-150
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-10-05  AI Skill        NEW: Daily 03:00 UTC task calling AEROSPACE_PARTS_PIPELINE
==============================================================*/
CREATE OR REPLACE TASK AEROSPACE_PARTS_PIPELINE_TASK
    WAREHOUSE = W_IN_CAPG_BIONIC_PMI_POC_XS
    SCHEDULE  = 'USING CRON 0 3 * * * UTC'
AS
CALL AEROSPACE_PARTS_PIPELINE('INCREMENTAL');