/*==============================================================
 File Name        : AEROSPACE_PARTS_TARGET.sql
 Object Name      : AEROSPACE_PARTS_TARGET
 Project          : SCRUM-150
 Purpose          : Target table DDL — Aerospace Parts Inventory analytics-ready target with risk classification
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-10-05
 Work Item        : SCRUM-150
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-10-05  AI Skill        NEW: Target table with SUPPLY_RISK_LEVEL, RECORD_STATUS, DW audit columns
==============================================================*/
CREATE OR ALTER TABLE AEROSPACE_PARTS_TARGET (
    PART_NUMBER           VARCHAR(100)    NOT NULL,
    PART_DESCRIPTION      VARCHAR(500),
    MANUFACTURER          VARCHAR(300),
    WEIGHT_KG             NUMBER(12,4),
    CERTIFICATION_STATUS  VARCHAR(50),
    LEAD_TIME_DAYS        NUMBER(10),
    UNIT_PRICE_USD        NUMBER(18,2),
    QUANTITY_ON_HAND      NUMBER(12),
    CATEGORY              VARCHAR(100),
    UPDATED_AT            TIMESTAMP_NTZ   NOT NULL,
    SUPPLY_RISK_LEVEL     VARCHAR(20)     NOT NULL DEFAULT 'Medium Risk',
    RECORD_STATUS         VARCHAR(20)     NOT NULL DEFAULT 'Active',
    DW_INSERT_TS          TIMESTAMP_NTZ   NOT NULL,
    DW_UPDATE_TS          TIMESTAMP_NTZ   NOT NULL,
    CONSTRAINT PK_AEROSPACE_PARTS_TARGET PRIMARY KEY (PART_NUMBER)
);