/*==============================================================
 File Name        : AEROSPACE_PARTS_PIPELINE.sql
 Object Name      : AEROSPACE_PARTS_PIPELINE
 Project          : SCRUM-150
 Purpose          : SCD Type 1 incremental pipeline — AEROSPACE_PARTS_SOURCE to AEROSPACE_PARTS_TARGET
                    Implements: watermark-based incremental load, deduplication by UPDATED_AT,
                    CamelCase MANUFACTURER, WEIGHT_KG null-guard, SUPPLY_RISK_LEVEL derivation,
                    soft delete (Decommissioned), mandatory ETL_RECONCILIATION_LOG per run.
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-10-05
 Work Item        : SCRUM-150
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-10-05  AI Skill        NEW: Full pipeline from BRD — SCD1, incremental, soft delete, recon log
==============================================================*/
CREATE OR REPLACE PROCEDURE AEROSPACE_PARTS_PIPELINE(
    P_MODE VARCHAR DEFAULT 'INCREMENTAL'
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_run_start         TIMESTAMP_NTZ   := CURRENT_TIMESTAMP();
    v_run_end           TIMESTAMP_NTZ;
    v_load_mode         VARCHAR         := UPPER(P_MODE);
    v_watermark_from    TIMESTAMP_NTZ;
    v_watermark_to      TIMESTAMP_NTZ   := CURRENT_TIMESTAMP();
    v_source_count      NUMBER          := 0;
    v_target_count      NUMBER          := 0;
    v_inserted          NUMBER          := 0;
    v_updated           NUMBER          := 0;
    v_decommissioned    NUMBER          := 0;
    v_invalid_cert      NUMBER          := 0;
    v_status            VARCHAR         := 'SUCCESS';
    v_error_msg         VARCHAR         := NULL;
BEGIN

    -- ============================================================
    -- SECTION 1: WATERMARK RESOLUTION
    -- Incremental: derive watermark from last successful run.
    -- First run or FULL mode: watermark_from = NULL (full load).
    -- ============================================================
    IF (v_load_mode = 'INCREMENTAL') THEN
        SELECT MAX(WATERMARK_TO)
        INTO   :v_watermark_from
        FROM   ETL_RECONCILIATION_LOG
        WHERE  PIPELINE_NAME = 'AEROSPACE_PARTS_PIPELINE'
          AND  PIPELINE_STATUS = 'SUCCESS';
    END IF;

    IF (:v_watermark_from IS NULL) THEN
        v_load_mode := 'FULL';
    END IF;

    -- ============================================================
    -- SECTION 2: STAGED EXTRACTION WITH DEDUPLICATION
    -- Extract from source filtered by watermark.
    -- Deduplicate: retain latest UPDATED_AT per PART_NUMBER.
    -- Apply all transformations per BRD.
    -- ============================================================
    CREATE OR REPLACE TEMPORARY TABLE STAGED_AEROSPACE_PARTS AS
    SELECT
        src.PART_NUMBER,
        src.PART_DESCRIPTION,
        INITCAP(src.MANUFACTURER)                                       AS MANUFACTURER,
        CASE WHEN src.WEIGHT_KG <= 0 THEN NULL ELSE src.WEIGHT_KG END  AS WEIGHT_KG,
        src.CERTIFICATION_STATUS,
        src.LEAD_TIME_DAYS,
        ROUND(src.UNIT_PRICE_USD, 2)                                    AS UNIT_PRICE_USD,
        src.QUANTITY_ON_HAND,
        src.CATEGORY,
        src.UPDATED_AT,
        CASE
            WHEN src.CERTIFICATION_STATUS = 'Pending'
                 AND src.LEAD_TIME_DAYS > 90                            THEN 'High Risk'
            WHEN src.CERTIFICATION_STATUS = 'Pending'
                 OR  src.LEAD_TIME_DAYS > 100                           THEN 'Medium Risk'
            WHEN src.CERTIFICATION_STATUS IN ('FAA', 'EASA', 'Dual')
                 AND src.LEAD_TIME_DAYS <= 60                           THEN 'Low Risk'
            ELSE 'Medium Risk'
        END                                                             AS SUPPLY_RISK_LEVEL
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (
                   PARTITION BY PART_NUMBER
                   ORDER BY UPDATED_AT DESC
               ) AS rn
        FROM   AEROSPACE_PARTS_SOURCE
        WHERE  (:v_watermark_from IS NULL OR UPDATED_AT > :v_watermark_from)
          AND  PART_NUMBER IS NOT NULL
    ) src
    WHERE src.rn = 1;

    SELECT COUNT(*) INTO :v_source_count FROM STAGED_AEROSPACE_PARTS;

    SELECT COUNT(*) INTO :v_invalid_cert
    FROM   STAGED_AEROSPACE_PARTS
    WHERE  CERTIFICATION_STATUS IS NULL
       OR  CERTIFICATION_STATUS NOT IN ('Pending', 'FAA', 'EASA', 'Dual');

    -- ============================================================
    -- SECTION 3: SCD TYPE 1 MERGE (UPSERT)
    -- Business key: PART_NUMBER
    -- On match: overwrite all non-key fields (SCD Type 1).
    -- On no match: insert as new Active record.
    -- ============================================================
    MERGE INTO AEROSPACE_PARTS_TARGET tgt
    USING STAGED_AEROSPACE_PARTS stg
    ON tgt.PART_NUMBER = stg.PART_NUMBER
    WHEN MATCHED THEN
        UPDATE SET
            tgt.PART_DESCRIPTION      = stg.PART_DESCRIPTION,
            tgt.MANUFACTURER          = stg.MANUFACTURER,
            tgt.WEIGHT_KG             = stg.WEIGHT_KG,
            tgt.CERTIFICATION_STATUS  = stg.CERTIFICATION_STATUS,
            tgt.LEAD_TIME_DAYS        = stg.LEAD_TIME_DAYS,
            tgt.UNIT_PRICE_USD        = stg.UNIT_PRICE_USD,
            tgt.QUANTITY_ON_HAND      = stg.QUANTITY_ON_HAND,
            tgt.CATEGORY              = stg.CATEGORY,
            tgt.UPDATED_AT            = stg.UPDATED_AT,
            tgt.SUPPLY_RISK_LEVEL     = stg.SUPPLY_RISK_LEVEL,
            tgt.RECORD_STATUS         = 'Active',
            tgt.DW_UPDATE_TS          = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN
        INSERT (
            PART_NUMBER, PART_DESCRIPTION, MANUFACTURER, WEIGHT_KG,
            CERTIFICATION_STATUS, LEAD_TIME_DAYS, UNIT_PRICE_USD,
            QUANTITY_ON_HAND, CATEGORY, UPDATED_AT,
            SUPPLY_RISK_LEVEL, RECORD_STATUS, DW_INSERT_TS, DW_UPDATE_TS
        )
        VALUES (
            stg.PART_NUMBER, stg.PART_DESCRIPTION, stg.MANUFACTURER, stg.WEIGHT_KG,
            stg.CERTIFICATION_STATUS, stg.LEAD_TIME_DAYS, stg.UNIT_PRICE_USD,
            stg.QUANTITY_ON_HAND, stg.CATEGORY, stg.UPDATED_AT,
            stg.SUPPLY_RISK_LEVEL, 'Active', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
        );

    SELECT COUNT(*) INTO :v_inserted
    FROM   AEROSPACE_PARTS_TARGET
    WHERE  DW_INSERT_TS >= :v_run_start;

    SELECT COUNT(*) INTO :v_updated
    FROM   AEROSPACE_PARTS_TARGET
    WHERE  DW_UPDATE_TS >= :v_run_start
      AND  DW_INSERT_TS  < :v_run_start;

    -- ============================================================
    -- SECTION 4: SOFT DELETE — DECOMMISSION MISSING RECORDS
    -- Records in TARGET whose PART_NUMBER is absent from the
    -- current source batch are marked Decommissioned.
    -- ============================================================
    UPDATE AEROSPACE_PARTS_TARGET tgt
    SET    tgt.RECORD_STATUS = 'Decommissioned',
           tgt.DW_UPDATE_TS  = CURRENT_TIMESTAMP()
    WHERE  tgt.RECORD_STATUS = 'Active'
      AND  tgt.PART_NUMBER NOT IN (SELECT PART_NUMBER FROM STAGED_AEROSPACE_PARTS);

    SELECT COUNT(*) INTO :v_decommissioned
    FROM   AEROSPACE_PARTS_TARGET
    WHERE  RECORD_STATUS = 'Decommissioned'
      AND  DW_UPDATE_TS  >= :v_run_start;

    SELECT COUNT(*) INTO :v_target_count
    FROM   AEROSPACE_PARTS_TARGET
    WHERE  RECORD_STATUS = 'Active';

    -- ============================================================
    -- SECTION 5: RECONCILIATION LOGGING
    -- Mandatory per BRD FR-005. One row per pipeline run.
    -- Captures all run metrics for compliance and audit.
    -- ============================================================
    v_run_end := CURRENT_TIMESTAMP();

    INSERT INTO ETL_RECONCILIATION_LOG (
        PIPELINE_NAME, RUN_START_TS, RUN_END_TS, LOAD_MODE,
        WATERMARK_FROM, WATERMARK_TO,
        SOURCE_ROW_COUNT, TARGET_ROW_COUNT,
        INSERTED_COUNT, UPDATED_COUNT, DECOMMISSIONED_COUNT, INVALID_CERT_COUNT,
        PIPELINE_STATUS, ERROR_MESSAGE, RUN_DURATION_SECONDS
    )
    VALUES (
        'AEROSPACE_PARTS_PIPELINE', :v_run_start, :v_run_end, :v_load_mode,
        :v_watermark_from, :v_watermark_to,
        :v_source_count, :v_target_count,
        :v_inserted, :v_updated, :v_decommissioned, :v_invalid_cert,
        :v_status, :v_error_msg,
        DATEDIFF('second', :v_run_start, :v_run_end)
    );

    RETURN 'SUCCESS | Mode=' || :v_load_mode
        || ' | Src='     || :v_source_count
        || ' | Ins='     || :v_inserted
        || ' | Upd='     || :v_updated
        || ' | Decomm='  || :v_decommissioned
        || ' | InvalidCert=' || :v_invalid_cert;

EXCEPTION
    WHEN OTHER THEN
        v_status    := 'FAILED';
        v_error_msg := SQLERRM;
        v_run_end   := CURRENT_TIMESTAMP();

        INSERT INTO ETL_RECONCILIATION_LOG (
            PIPELINE_NAME, RUN_START_TS, RUN_END_TS, LOAD_MODE,
            WATERMARK_FROM, WATERMARK_TO,
            SOURCE_ROW_COUNT, TARGET_ROW_COUNT,
            INSERTED_COUNT, UPDATED_COUNT, DECOMMISSIONED_COUNT, INVALID_CERT_COUNT,
            PIPELINE_STATUS, ERROR_MESSAGE, RUN_DURATION_SECONDS
        )
        VALUES (
            'AEROSPACE_PARTS_PIPELINE', :v_run_start, :v_run_end, :v_load_mode,
            :v_watermark_from, :v_watermark_to,
            :v_source_count, :v_target_count,
            0, 0, 0, 0,
            :v_status, :v_error_msg,
            DATEDIFF('second', :v_run_start, :v_run_end)
        );

        RETURN 'FAILED | ' || :v_error_msg;
END;
$$;