/*==============================================================
 File Name        : AEROSPACE_PARTS_SOURCE.sql
 Object Name      : AEROSPACE_PARTS_SOURCE
 Project          : SCRUM-150
 Purpose          : Source table DDL — Aerospace Parts Inventory raw source
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-10-05
 Work Item        : SCRUM-150
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-10-05  AI Skill        NEW: Source table for aerospace parts inventory pipeline
==============================================================*/
CREATE OR ALTER TABLE AEROSPACE_PARTS_SOURCE (
    PART_NUMBER           VARCHAR(100)    NOT NULL,
    PART_DESCRIPTION      VARCHAR(500),
    MANUFACTURER          VARCHAR(300),
    WEIGHT_KG             NUMBER(12,4),
    CERTIFICATION_STATUS  VARCHAR(50),
    LEAD_TIME_DAYS        NUMBER(10),
    UNIT_PRICE_USD        NUMBER(18,2),
    QUANTITY_ON_HAND      NUMBER(12),
    CATEGORY              VARCHAR(100),
    UPDATED_AT            TIMESTAMP_NTZ   NOT NULL
);