/*==============================================================
 File Name        : ETL_RECONCILIATION_LOG.sql
 Object Name      : ETL_RECONCILIATION_LOG
 Project          : SCRUM-150
 Purpose          : Reconciliation log table DDL — mandatory per-run audit for aerospace parts pipeline
 Generated By     : AI Skill — SDLC
 Generated Date   : 2026-10-05
 Work Item        : SCRUM-150
 Modification History:
 ---------------------------------------------------------------
 Date        Author          Description
 ---------------------------------------------------------------
 2026-10-05  AI Skill        NEW: Reconciliation log for aerospace parts pipeline per FR-005
==============================================================*/
CREATE OR ALTER TABLE ETL_RECONCILIATION_LOG (
    LOG_ID                NUMBER          AUTOINCREMENT PRIMARY KEY,
    PIPELINE_NAME         VARCHAR(200)    NOT NULL,
    RUN_START_TS          TIMESTAMP_NTZ   NOT NULL,
    RUN_END_TS            TIMESTAMP_NTZ,
    LOAD_MODE             VARCHAR(20)     NOT NULL,
    WATERMARK_FROM        TIMESTAMP_NTZ,
    WATERMARK_TO          TIMESTAMP_NTZ,
    SOURCE_ROW_COUNT      NUMBER          DEFAULT 0,
    TARGET_ROW_COUNT      NUMBER          DEFAULT 0,
    INSERTED_COUNT        NUMBER          DEFAULT 0,
    UPDATED_COUNT         NUMBER          DEFAULT 0,
    DECOMMISSIONED_COUNT  NUMBER          DEFAULT 0,
    INVALID_CERT_COUNT    NUMBER          DEFAULT 0,
    PIPELINE_STATUS       VARCHAR(20)     NOT NULL,
    ERROR_MESSAGE         VARCHAR(2000),
    RUN_DURATION_SECONDS  NUMBER(10,2)
);