/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_SOURCE
Purpose     : Source table DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS AEROSPACE_PARTS_SOURCE (
    PART_NUMBER             VARCHAR(50)         NOT NULL,
    MANUFACTURER            VARCHAR(100),
    WEIGHT_KG               NUMBER(10,4),
    UNIT_PRICE_USD          NUMBER(14,2),
    CERTIFICATION_STATUS    VARCHAR(20),
    LEAD_TIME_DAYS          NUMBER(6),
    LIFECYCLE_STATUS        VARCHAR(50),
    INSTALLATION_DATE       DATE,
    UPDATED_AT              TIMESTAMP_NTZ,
    STATUS                  VARCHAR(30)
);

-- SECTION 2: Constraints
ALTER TABLE AEROSPACE_PARTS_SOURCE
    ADD CONSTRAINT IF NOT EXISTS PK_APS_PART_NUMBER PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- Staging table. UPDATED_AT drives incremental watermark logic.
-- CERTIFICATION_STATUS values: FAA, EASA, Dual, Pending.