/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_TARGET
Purpose     : Target table DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

-- ============================================================
-- FILE        : DDL_AEROSPACE_PARTS_TARGET.sql
-- TYPE        : DDL_TARGET
-- DATABASE    : GEN_AI_POC_SNOWFLAKECOE
-- SCHEMA      : SDLC_WIZARD
-- WAREHOUSE   : W_CAPG_APAC_IND_DEMO_IDEA_REFACTOR_SOL_XS
-- DESCRIPTION : Target analytics table for aerospace parts
--               inventory. Populated by SCD Type 1 MERGE via
--               SP_LOAD_AEROSPACE_PARTS_SCD1. Supports
--               reporting, compliance, and procurement analysis.
-- ============================================================

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE W_CAPG_APAC_IND_DEMO_IDEA_REFACTOR_SOL_XS;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET (

    -- --------------------------------------------------------
    -- SURROGATE KEY
    -- --------------------------------------------------------
    PARTS_TARGET_SK         NUMBER AUTOINCREMENT START 1 INCREMENT 1
        COMMENT 'Surrogate key. System-generated sequential identifier for the target record.',

    -- --------------------------------------------------------
    -- PRIMARY BUSINESS KEY
    -- --------------------------------------------------------
    PART_NUMBER             VARCHAR(100)      NOT NULL        -- Business key; MERGE join condition in SP_LOAD_AEROSPACE_PARTS_SCD1
        COMMENT 'Business key from source. SCD1 MERGE join key. Must be unique in target. [DELTA AC-001] Deduplication via ROW_NUMBER() PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC applied in staging CTE before MERGE.',

    -- --------------------------------------------------------
    -- PART DESCRIPTORS
    -- --------------------------------------------------------
    PART_NAME               VARCHAR(255)                      -- Part name carried through from source
        COMMENT 'Descriptive part name. SCD1: overwritten on match.',

    PART_CATEGORY           VARCHAR(100)                      -- Functional category grouping
        COMMENT 'Part functional category. SCD1: overwritten on match.',

    PART_STATUS             VARCHAR(50)                       -- Operational status; set to Decommissioned by soft-delete logic
        COMMENT 'Operational status. [DELTA AC-007] After MERGE, records absent from staging are SET to Decommissioned if not already.',

    LIFECYCLE_STATUS        VARCHAR(50)                       -- [DELTA] AC-005: Lifecycle flag included in MERGE SET clause
        COMMENT '[DELTA AC-005] Lifecycle status from source included in MERGE matched/not-matched clauses.',

    -- --------------------------------------------------------
    -- MANUFACTURER (TRANSFORMED)
    -- --------------------------------------------------------
    MANUFACTURER            VARCHAR(255)                      -- Uppercased manufacturer name (pipeline transformation)
        COMMENT 'Manufacturer name. Pipeline applies UPPER(MANUFACTURER) transformation before load.',

    SUPPLIER_CODE           VARCHAR(50)
        COMMENT 'Supplier code for procurement cross-reference.',

    COUNTRY_OF_ORIGIN       VARCHAR(100)
        COMMENT 'Country of manufacture for compliance and trade reporting.',

    -- --------------------------------------------------------
    -- PHYSICAL ATTRIBUTES (TRANSFORMED)
    -- --------------------------------------------------------
    WEIGHT_KG               NUMBER(12, 4)                     -- Nullified if source value <= 0
        COMMENT '[DELTA AC-003] CASE WHEN WEIGHT_KG <= 0 THEN NULL ELSE WEIGHT_KG END applied in staging CTE.',

    DIMENSIONS_CM           VARCHAR(100)
        COMMENT 'Physical dimensions for logistics planning.',

    -- --------------------------------------------------------
    -- FINANCIAL ATTRIBUTES (TRANSFORMED)
    -- --------------------------------------------------------
    UNIT_PRICE_USD          NUMBER(18, 2)                     -- Rounded to 2 decimal places
        COMMENT 'Unit price in USD. Pipeline applies ROUND(UNIT_PRICE_USD, 2) before load.',

    CURRENCY_CODE           VARCHAR(10)       DEFAULT 'USD'
        COMMENT 'ISO currency code for UNIT_PRICE_USD.',

    -- --------------------------------------------------------
    -- CERTIFICATION & COMPLIANCE
    -- --------------------------------------------------------
    CERTIFICATION_STATUS    VARCHAR(50)                       -- Used in RISK_SCORE derivation
        COMMENT 'Regulatory certification (FAA, EASA, Dual, Pending). Input to RISK_SCORE CASE logic. [DELTA AC-006]',

    COMPLIANCE_FLAG         VARCHAR(10)
        COMMENT 'High-level compliance indicator (Y/N).',

    -- --------------------------------------------------------
    -- PROCUREMENT & LEAD TIME
    -- --------------------------------------------------------
    LEAD_TIME_DAYS          NUMBER(6, 0)                      -- Used in RISK_SCORE derivation
        COMMENT 'Procurement lead time in days. Input to RISK_SCORE CASE logic. [DELTA AC-006]',

    REORDER_POINT           NUMBER(10, 0)
        COMMENT 'Inventory reorder threshold.',

    STOCK_QUANTITY          NUMBER(12, 0)
        COMMENT 'On-hand stock quantity.',

    -- --------------------------------------------------------
    -- INSTALLATION & LIFECYCLE DATES
    -- --------------------------------------------------------
    INSTALLATION_DATE       DATE                              -- Used in exclusion filter evaluation
        COMMENT 'Installation date. [DELTA AC-005] Exclusion filter: LIFECYCLE_STATUS=End of Life AND INSTALLATION_DATE < DATEADD(year,-3,CURRENT_DATE()) records are excluded from load.',

    DECOMMISSION_DATE       DATE
        COMMENT 'Planned or actual decommission date.',

    MANUFACTURE_DATE        DATE
        COMMENT 'Date of manufacture for traceability.',

    -- --------------------------------------------------------
    -- DERIVED RISK SCORE (PIPELINE-COMPUTED)
    -- [DELTA AC-006] Full CASE expression applied in staging CTE:
    --   WHEN CERTIFICATION_STATUS='Pending' AND LEAD_TIME_DAYS>90  => HIGH
    --   WHEN CERTIFICATION_STATUS='Pending' OR  LEAD_TIME_DAYS>120 => MEDIUM
    --   WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual')
    --        AND LEAD_TIME_DAYS<=60                                 => LOW
    --   ELSE MEDIUM
    -- --------------------------------------------------------
    RISK_SCORE              VARCHAR(20)                       -- Pipeline-derived: HIGH / MEDIUM / LOW
        COMMENT '[DELTA AC-006] Pipeline-derived risk classification. CASE logic evaluates CERTIFICATION_STATUS and LEAD_TIME_DAYS. Overwrites source value on every SCD1 MERGE.',

    CRITICALITY_LEVEL       VARCHAR(50)
        COMMENT 'Operational criticality designation.',

    -- --------------------------------------------------------
    -- AUDIT & WATERMARK COLUMNS (SOURCE-CARRIED)
    -- --------------------------------------------------------
    CREATED_AT              TIMESTAMP_NTZ
        COMMENT 'Original record creation timestamp from source system.',

    UPDATED_AT              TIMESTAMP_NTZ                     -- Watermark column; MAX value stored in ETL_RECONCILIATION_LOG
        COMMENT 'Source last-modified timestamp. [DELTA AC-009] MAX(UPDATED_AT) from successful run written to ETL_RECONCILIATION_LOG as next watermark.',

    SOURCE_SYSTEM           VARCHAR(100)
        COMMENT 'Source system identifier for lineage.',

    BATCH_ID                VARCHAR(100)
        COMMENT 'Upstream batch identifier for traceability.',

    -- --------------------------------------------------------
    -- PIPELINE AUDIT COLUMNS (TARGET-MANAGED)
    -- --------------------------------------------------------
    PIPELINE_LOAD_TS        TIMESTAMP_NTZ     DEFAULT CURRENT_TIMESTAMP()
        COMMENT 'Timestamp when this record was last written by SP_LOAD_AEROSPACE_PARTS_SCD1.',

    PIPELINE_RUN_ID         VARCHAR(100)
        COMMENT 'Unique run identifier from ETL_RECONCILIATION_LOG.RUN_ID for end-to-end traceability.',

    PIPELINE_ACTION         VARCHAR(20)                       -- INSERT / UPDATE / SOFT_DELETE
        COMMENT 'Last action performed by pipeline on this record: INSERT (new), UPDATE (SCD1 overwrite), SOFT_DELETE (Decommissioned by AC-007 logic).',

    -- --------------------------------------------------------
    -- TABLE CONSTRAINTS
    -- --------------------------------------------------------
    CONSTRAINT PK_AEROSPACE_PARTS_TARGET PRIMARY KEY (PART_NUMBER)

)
COMMENT = 'TARGET TABLE: Analytics-ready aerospace parts inventory. Loaded daily at 02:00 UTC by SP_LOAD_AEROSPACE_PARTS_SCD1 via SCD Type 1 MERGE. Applies transformations: MANUFACTURER UPPER, WEIGHT_KG nullification (AC-003), UNIT_PRICE_USD rounding, RISK_