/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_SOURCE
Purpose     : Source table DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

-- ============================================================
-- FILE        : DDL_AEROSPACE_PARTS_SOURCE.sql
-- TYPE        : DDL_SOURCE
-- DATABASE    : GEN_AI_POC_SNOWFLAKECOE
-- SCHEMA      : SDLC_WIZARD
-- WAREHOUSE   : W_CAPG_APAC_IND_DEMO_IDEA_REFACTOR_SOL_XS
-- DESCRIPTION : Source staging table for aerospace parts
--               inventory data. This table represents the
--               upstream feed consumed by the pipeline
--               SP_LOAD_AEROSPACE_PARTS_SCD1.
-- ============================================================

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE W_CAPG_APAC_IND_DEMO_IDEA_REFACTOR_SOL_XS;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE (

    -- --------------------------------------------------------
    -- PRIMARY BUSINESS KEY
    -- --------------------------------------------------------
    PART_NUMBER             VARCHAR(100)      NOT NULL        -- Unique identifier for each aerospace part (business key for SCD1 merge)
        COMMENT 'Business key. Must be unique per part. Used as MERGE join key in SP_LOAD_AEROSPACE_PARTS_SCD1.',

    -- --------------------------------------------------------
    -- PART DESCRIPTORS
    -- --------------------------------------------------------
    PART_NAME               VARCHAR(255)                      -- Human-readable name of the part
        COMMENT 'Descriptive name of the aerospace part.',

    PART_CATEGORY           VARCHAR(100)                      -- High-level category (e.g., Avionics, Structural, Propulsion)
        COMMENT 'Functional category grouping for the part.',

    PART_STATUS             VARCHAR(50)                       -- Operational status (e.g., Active, Inactive, Decommissioned)
        COMMENT 'Operational lifecycle status of the part. Soft-delete target field in pipeline.',

    LIFECYCLE_STATUS        VARCHAR(50)                       -- [DELTA] AC-005: Fine-grained lifecycle flag (e.g., End of Life, Active, Deprecated)
        COMMENT '[DELTA AC-005] Used in exclusion filter: records with End of Life AND INSTALLATION_DATE < 3 years ago are excluded from pipeline load.',

    -- --------------------------------------------------------
    -- MANUFACTURER & SUPPLIER
    -- --------------------------------------------------------
    MANUFACTURER            VARCHAR(255)                      -- Manufacturer name; uppercased by pipeline transformation
        COMMENT 'Manufacturer name. Pipeline applies UPPER() transformation on load.',

    SUPPLIER_CODE           VARCHAR(50)                       -- Supplier identifier code
        COMMENT 'Procurement supplier code for cross-reference.',

    COUNTRY_OF_ORIGIN       VARCHAR(100)                      -- Country where the part is manufactured
        COMMENT 'Country of manufacture; used for compliance and trade reporting.',

    -- --------------------------------------------------------
    -- PHYSICAL ATTRIBUTES
    -- --------------------------------------------------------
    WEIGHT_KG               NUMBER(12, 4)                     -- Weight in kilograms; zero or negative values treated as NULL by pipeline
        COMMENT 'Part weight in kilograms. [DELTA AC-003] Pipeline nullifies values <= 0.',

    DIMENSIONS_CM           VARCHAR(100)                      -- Dimensional specification (L x W x H in cm)
        COMMENT 'Physical dimensions string for logistics and storage planning.',

    -- --------------------------------------------------------
    -- FINANCIAL ATTRIBUTES
    -- --------------------------------------------------------
    UNIT_PRICE_USD          NUMBER(18, 4)                     -- Unit price in USD; rounded to 2 decimal places by pipeline
        COMMENT 'Unit cost in USD. Pipeline applies ROUND(..., 2) transformation.',

    CURRENCY_CODE           VARCHAR(10)       DEFAULT 'USD'   -- ISO currency code
        COMMENT 'Currency denomination for UNIT_PRICE_USD.',

    -- --------------------------------------------------------
    -- CERTIFICATION & COMPLIANCE
    -- --------------------------------------------------------
    CERTIFICATION_STATUS    VARCHAR(50)                       -- Regulatory certification (e.g., FAA, EASA, Dual, Pending)
        COMMENT 'Regulatory certification status. Used in RISK_SCORE derivation logic. [DELTA AC-006]',

    COMPLIANCE_FLAG         VARCHAR(10)                       -- Boolean-style compliance indicator (Y/N)
        COMMENT 'High-level compliance flag for regulatory reporting.',

    -- --------------------------------------------------------
    -- PROCUREMENT & LEAD TIME
    -- --------------------------------------------------------
    LEAD_TIME_DAYS          NUMBER(6, 0)                      -- Procurement lead time in days; used in RISK_SCORE derivation
        COMMENT 'Procurement lead time in calendar days. Used in RISK_SCORE CASE logic. [DELTA AC-006]',

    REORDER_POINT           NUMBER(10, 0)                     -- Inventory reorder threshold quantity
        COMMENT 'Quantity level that triggers procurement reorder.',

    STOCK_QUANTITY          NUMBER(12, 0)                     -- Current on-hand stock quantity
        COMMENT 'Current inventory quantity on hand.',

    -- --------------------------------------------------------
    -- INSTALLATION & LIFECYCLE DATES
    -- --------------------------------------------------------
    INSTALLATION_DATE       DATE                              -- Date the part was installed or placed into service
        COMMENT 'Installation date. Used in End of Life exclusion filter: INSTALLATION_DATE < DATEADD(year,-3,CURRENT_DATE()). [DELTA AC-005]',

    DECOMMISSION_DATE       DATE                              -- Planned or actual decommission date
        COMMENT 'Planned or actual decommission date for lifecycle management.',

    MANUFACTURE_DATE        DATE                              -- Date of manufacture
        COMMENT 'Part manufacture date for traceability and shelf-life calculations.',

    -- --------------------------------------------------------
    -- CLASSIFICATION & RISK
    -- --------------------------------------------------------
    RISK_SCORE              VARCHAR(20)                       -- Pre-classified risk score from source; may be overridden by pipeline
        COMMENT 'Source-provided risk classification. Pipeline derives and overwrites this field. [DELTA AC-006]',

    CRITICALITY_LEVEL       VARCHAR(50)                       -- Operational criticality (e.g., Mission Critical, Standard)
        COMMENT 'Operational criticality designation for prioritisation.',

    -- --------------------------------------------------------
    -- AUDIT & WATERMARK COLUMNS
    -- --------------------------------------------------------
    CREATED_AT              TIMESTAMP_NTZ     NOT NULL        -- Record creation timestamp
        COMMENT 'Timestamp when the record was created in the source system.',

    UPDATED_AT              TIMESTAMP_NTZ     NOT NULL        -- Last update timestamp; used as incremental watermark by pipeline
        COMMENT 'Last modification timestamp. [DELTA AC-009] Used as incremental watermark: pipeline reads MAX successful UPDATED_AT from ETL_RECONCILIATION_LOG.',

    SOURCE_SYSTEM           VARCHAR(100)                      -- Originating source system identifier
        COMMENT 'Source system name for lineage and auditability.',

    BATCH_ID                VARCHAR(100)                      -- Batch/load identifier from upstream feed
        COMMENT 'Upstream batch identifier for traceability.',

    -- --------------------------------------------------------
    -- TABLE CONSTRAINTS
    -- --------------------------------------------------------
    CONSTRAINT PK_AEROSPACE_PARTS_SOURCE PRIMARY KEY (PART_NUMBER)

)
COMMENT = 'SOURCE TABLE: Upstream aerospace parts inventory feed consumed daily by SP_LOAD_AEROSPACE_PARTS_SCD1. Schema is out-of-scope for modification per BRD. LIFECYCLE_STATUS and INSTALLATION_DATE are key fields for exclusion filter logic (AC-005). UPDATED_AT drives incremental watermark (AC-009).'
DATA_RETENTION_TIME_IN_DAYS = 1
;