/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : ETL reconciliation log DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS ETL_RECONCILIATION_LOG (
    RUN_ID                  VARCHAR(100)        NOT NULL,
    RUN_TIMESTAMP           TIMESTAMP_NTZ       DEFAULT CURRENT_TIMESTAMP(),
    WATERMARK_USED          TIMESTAMP_NTZ,
    SOURCE_COUNT            NUMBER(18),
    INSERTED_COUNT          NUMBER(18),
    UPDATED_COUNT           NUMBER(18),
    DECOMMISSIONED_COUNT    NUMBER(18),
    STATUS                  VARCHAR(20),
    ERROR_MESSAGE           VARCHAR(2000),
    NEW_WATERMARK           TIMESTAMP_NTZ
);

-- SECTION 2: Constraints
ALTER TABLE ETL_RECONCILIATION_LOG
    ADD CONSTRAINT IF NOT EXISTS PK_ERL_RUN_ID PRIMARY KEY (RUN_ID);

-- SECTION 3: Notes
-- One row per SP execution. STATUS: SUCCESS | FAILED.
-- NEW_WATERMARK stored here and read on next incremental run.