/*=========================================================
Object Name : SP_AEROSPACE_PARTS_PIPELINE
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_AEROSPACE_PARTS_PIPELINE(
    P_MODE VARCHAR DEFAULT 'INCREMENTAL'
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS $$
DECLARE
    -- SECTION 1: Variables
    v_run_id          VARCHAR;
    v_source_count    INTEGER;
    v_target_count    INTEGER;
    v_expected_count  INTEGER;
    v_discrepancy     INTEGER;
    v_max_watermark   TIMESTAMP_NTZ;
    v_extracted_count INTEGER;
    v_watermark_val   TIMESTAMP_NTZ;
    -- [DELTA ADD_COLUMN] STORED_PROCEDURE_NAME — Added per delta analysis
    v_sp_name         VARCHAR DEFAULT 'SP_AEROSPACE_PARTS_PIPELINE';
    -- [DELTA ADD_COLUMN] BUSINESS_KEY — Added per delta analysis
    v_business_key    VARCHAR DEFAULT 'PART_NUMBER';
    -- [DELTA ADD_COLUMN] DUE_DATE — Added per delta analysis
    v_due_date        DATE    DEFAULT CURRENT_DATE();
BEGIN
    v_run_id := UUID_STRING();

    -- SECTION 2: Source Processing
    -- Resolve incremental watermark
    IF (:P_MODE = 'INCREMENTAL') THEN
        SELECT COALESCE(MAX(WATERMARK_VALUE), '1900-01-01'::TIMESTAMP_NTZ)
        INTO   :v_watermark_val
        FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_WATERMARK
        WHERE  PIPELINE_NAME = :v_sp_name;
    ELSE
        v_watermark_val := '1900-01-01'::TIMESTAMP_NTZ;
    END IF;

    -- Staging: extract + deduplicate with ROW_NUMBER
    CREATE OR REPLACE TEMPORARY TABLE TMP_AEROSPACE_PARTS_STAGE AS
    SELECT
        PART_NUMBER,
        UPPER(MANUFACTURER)                                  AS MANUFACTURER,  -- UPPER transform
        CASE WHEN WEIGHT_KG <= 0 THEN -1 ELSE WEIGHT_KG END AS WEIGHT_KG,     -- sentinel replace
        LIFECYCLE_STATUS,
        INSTALLATION_DATE,
        CERTIFICATION_STATUS,
        LEAD_TIME_DAYS,
        STATUS,
        UPDATED_AT,
        -- SECTION 3: Data Validation
        CASE
            WHEN CERTIFICATION_STATUS = 'PENDING' AND LEAD_TIME_DAYS > 60  THEN 'High Risk'
            WHEN CERTIFICATION_STATUS = 'PENDING' OR  LEAD_TIME_DAYS > 100 THEN 'Medium Risk'
            WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual')
                 AND LEAD_TIME_DAYS <= 60                                   THEN 'Low Risk'
            ELSE 'Medium Risk'
        END AS RISK_SCORE,
        -- [DELTA ADD_COLUMN] STORED_PROCEDURE_NAME — Added per delta analysis
        :v_sp_name    AS STORED_PROCEDURE_NAME,
        -- [DELTA ADD_COLUMN] BUSINESS_KEY — Added per delta analysis
        :v_business_key AS BUSINESS_KEY,
        -- [DELTA ADD_COLUMN] DUE_DATE — Added per delta analysis
        :v_due_date   AS DUE_DATE,
        ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
    WHERE UPDATED_AT > :v_watermark_val;

    -- Keep only latest per PART_NUMBER (dedup)
    DELETE FROM TMP_AEROSPACE_PARTS_STAGE WHERE RN <> 1;

    -- SECTION 4: Merge Logic
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET  tgt
    USING TMP_AEROSPACE_PARTS_STAGE                                          src
    ON    tgt.PART_NUMBER = src.PART_NUMBER
    WHEN MATCHED THEN UPDATE SET
        tgt.MANUFACTURER         = src.MANUFACTURER,
        tgt.WEIGHT_KG            = src.WEIGHT_KG,
        tgt.LIFECYCLE_STATUS     = src.LIFECYCLE_STATUS,
        tgt.INSTALLATION_DATE    = src.INSTALLATION_DATE,
        tgt.CERTIFICATION_STATUS = src.CERTIFICATION_STATUS,
        tgt.LEAD_TIME_DAYS       = src.LEAD_TIME_DAYS,
        tgt.STATUS               = src.STATUS,
        tgt.RISK_SCORE           = src.RISK_SCORE,
        tgt.UPDATED_AT           = src.UPDATED_AT,
        -- [DELTA ADD_COLUMN] STORED_PROCEDURE_NAME — Added per delta analysis
        tgt.STORED_PROCEDURE_NAME = src.STORED_PROCEDURE_NAME,
        -- [DELTA ADD_COLUMN] BUSINESS_KEY — Added per delta analysis
        tgt.BUSINESS_KEY         = src.BUSINESS_KEY,
        -- [DELTA ADD_COLUMN] DUE_DATE — Added per delta analysis
        tgt.DUE_DATE             = src.DUE_DATE
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER, MANUFACTURER, WEIGHT_KG, LIFECYCLE_STATUS,
        INSTALLATION_DATE, CERTIFICATION_STATUS, LEAD_TIME_DAYS,
        STATUS, RISK_SCORE, UPDATED_AT,
        STORED_PROCEDURE_NAME, BUSINESS_KEY, DUE_DATE            -- [DELTA ADD_COLUMN] all three columns — Added per delta analysis
    ) VALUES (
        src.PART_NUMBER, src.MANUFACTURER, src.WEIGHT_KG, src.LIFECYCLE_STATUS,
        src.INSTALLATION_DATE, src.CERTIFICATION_STATUS, src.LEAD_TIME_DAYS,
        src.STATUS, src.RISK_SCORE, src.UPDATED_AT,
        src.STORED_PROCEDURE_NAME, src.BUSINESS_KEY, src.DUE_DATE
    );

    -- Soft delete: mark absent records as Decommissioned
    UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET tgt
    SET    tgt.STATUS = 'Decommissioned'
    WHERE  tgt.STATUS <> 'Decommissioned'
    AND    NOT EXISTS (
               SELECT 1
               FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE src
               WHERE  src.PART_NUMBER = tgt.PART_NUMBER
           );

    -- SECTION 5: Reconciliation
    SELECT COUNT(*) INTO :v_source_count
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE;

    SELECT COUNT(*) INTO :v_target_count
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;

    SELECT COUNT(*) INTO :v_expected_count
    FROM (
        SELECT DISTINCT PART_NUMBER
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE NOT (LIFECYCLE_STATUS = 'End of Life'
                   AND INSTALLATION_DATE < DATEADD(YEAR, -3, CURRENT_DATE()))
    );

    v_discrepancy := v_target_count - v_expected_count;

    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        PIPELINE_NAME, STEP_NAME,
        SOURCE_COUNT, TARGET_COUNT, EXPECTED_COUNT, DISCREPANCY, STATUS,
        -- [DELTA ADD_COLUMN] STORED_PROCEDURE_NAME — Added per delta analysis
        STORED_PROCEDURE_NAME,
        -- [DELTA ADD_COLUMN] BUSINESS_KEY — Added per delta analysis
        BUSINESS_KEY,
        -- [DELTA ADD_COLUMN] DUE_DATE — Added per delta analysis
        DUE_DATE
    ) VALUES (
        :v_sp_name, 'PIPELINE_COMPLETE',
        :v_source_count, :v_target_count, :v_expected_count, :v_discrepancy,
        CASE WHEN :v_discrepancy = 0 THEN 'SUCCESS' ELSE 'WARNING' END,
        :v_sp_name, :v_business_key, :v_due_date
    );

    -- Update watermark
    SELECT MAX(UPDATED_AT) INTO :v_max_watermark
    FROM   GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;

    SELECT COUNT(*) INTO :v_extracted_count
    FROM   TMP_AEROSPACE_PARTS_STAGE;

    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_WATERMARK (
        PIPELINE_NAME, WATERMARK_VALUE, ROW_COUNT, STATUS
    ) VALUES (
        :v_sp_name, :v_max_watermark, :v_extracted_count, 'SUCCESS'
    );

    RETURN 'Pipeline completed successfully in ' || :P_MODE || ' mode. '
        || 'Source: '   || :v_source_count
        || ', Target: ' || :v_target_count
        || ', Expected: '|| :v_expected_count
        || ', Discrepancy: ' || :v_discrepancy;

-- SECTION 6: Error Handling
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
            PIPELINE_NAME, STEP_NAME, STATUS, ERROR_MESSAGE,
            STORED_PROCEDURE_NAME, BUSINESS_KEY, DUE_DATE     -- [DELTA ADD_COLUMN] all three columns — Added per delta analysis
        ) VALUES (
            :v_sp_name, 'PIPELINE_ERROR', 'FAILED', SQLERRM,
            :v_sp_name, :v_business_key, :v_due_date
        );
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;