/*=========================================================
Object Name : SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    -- SECTION 1: Variables
    v_proc_name         VARCHAR DEFAULT 'SP_LOAD_AEROSPACE_PARTS_SCD1';
    v_watermark         TIMESTAMP_NTZ;
    v_watermark_str     VARCHAR;
    v_src_count         INTEGER DEFAULT 0;
    v_tgt_insert        INTEGER DEFAULT 0;
    v_tgt_update        INTEGER DEFAULT 0;
    v_tgt_delete        INTEGER DEFAULT 0;
    v_start_ts          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
    v_end_ts            TIMESTAMP_NTZ;
    v_status            VARCHAR DEFAULT 'SUCCESS';
    v_message           VARCHAR DEFAULT '';
    v_result            VARIANT;

BEGIN
    -- SECTION 2: Source Processing

    -- [DELTA] AC-009: Read last successful watermark from ETL_RECONCILIATION_LOG; default '1900-01-01'
    LET wm_rs RESULTSET := (
        SELECT COALESCE(MAX(WATERMARK_TS), '1900-01-01'::TIMESTAMP_NTZ) AS WM
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
        WHERE PROCEDURE_NAME = :v_proc_name
          AND STATUS = 'SUCCESS'
    );
    LET wm_cur CURSOR FOR wm_rs;
    OPEN wm_cur;
    FETCH wm_cur INTO v_watermark;
    CLOSE wm_cur;

    v_watermark_str := v_watermark::VARCHAR;

    -- SECTION 3: Data Validation

    -- Count qualifying source records after dedup and exclusion filters
    LET cnt_rs RESULTSET := (
        WITH DEDUPED AS (
            SELECT *,
                   ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN -- [DELTA] AC-001
            FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
            WHERE UPDATED_AT > :v_watermark
        ),
        STAGED AS (
            SELECT
                PART_NUMBER,
                PART_NAME,
                UPPER(MANUFACTURER)                                                   AS MANUFACTURER,
                CATEGORY,
                CASE WHEN WEIGHT_KG <= 0 THEN NULL ELSE WEIGHT_KG END                AS WEIGHT_KG, -- [DELTA] AC-003
                ROUND(UNIT_PRICE_USD, 2)                                              AS UNIT_PRICE_USD,
                CERTIFICATION_STATUS,
                LEAD_TIME_DAYS,
                PART_STATUS,
                LIFECYCLE_STATUS,                                                                   -- [DELTA] AC-005
                INSTALLATION_DATE,
                UPDATED_AT,
                CASE
                    WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 90  THEN 'HIGH'     -- [DELTA] AC-006
                    WHEN CERTIFICATION_STATUS = 'Pending' OR  LEAD_TIME_DAYS > 120 THEN 'MEDIUM'
                    WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 60 THEN 'LOW'
                    ELSE 'MEDIUM'
                END                                                                   AS RISK_SCORE
            FROM DEDUPED
            WHERE RN = 1
              AND NOT (                                                                             -- [DELTA] AC-005
                    LIFECYCLE_STATUS = 'End of Life'
                AND INSTALLATION_DATE < DATEADD(year, -3, CURRENT_DATE())
              )
        )
        SELECT COUNT(*) AS CNT FROM STAGED
    );
    LET cnt_cur CURSOR FOR cnt_rs;
    OPEN cnt_cur;
    FETCH cnt_cur INTO v_src_count;
    CLOSE cnt_cur;

    -- SECTION 4: Merge Logic

    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET T
    USING (
        WITH DEDUPED AS (
            SELECT *,
                   ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN -- [DELTA] AC-001
            FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
            WHERE UPDATED_AT > :v_watermark
        )
        SELECT
            PART_NUMBER,
            PART_NAME,
            UPPER(MANUFACTURER)                                                       AS MANUFACTURER,
            CATEGORY,
            CASE WHEN WEIGHT_KG <= 0 THEN NULL ELSE WEIGHT_KG END                    AS WEIGHT_KG, -- [DELTA] AC-003
            ROUND(UNIT_PRICE_USD, 2)                                                  AS UNIT_PRICE_USD,
            CERTIFICATION_STATUS,
            LEAD_TIME_DAYS,
            PART_STATUS,
            LIFECYCLE_STATUS,                                                                       -- [DELTA] AC-005
            INSTALLATION_DATE,
            UPDATED_AT,
            CASE
                WHEN CERTIFICATION_STATUS = 'Pending' AND LEAD_TIME_DAYS > 90  THEN 'HIGH'         -- [DELTA] AC-006
                WHEN CERTIFICATION_STATUS = 'Pending' OR  LEAD_TIME_DAYS > 120 THEN 'MEDIUM'
                WHEN CERTIFICATION_STATUS IN ('FAA','EASA','Dual') AND LEAD_TIME_DAYS <= 60 THEN 'LOW'
                ELSE 'MEDIUM'
            END                                                                       AS RISK_SCORE
        FROM DEDUPED
        WHERE RN = 1
          AND NOT (                                                                                 -- [DELTA] AC-005
                LIFECYCLE_STATUS = 'End of Life'
            AND INSTALLATION_DATE < DATEADD(year, -3, CURRENT_DATE())
          )
    ) S ON T.PART_NUMBER = S.PART_NUMBER
    WHEN MATCHED AND (
           T.PART_NAME            <> S.PART_NAME
        OR T.MANUFACTURER         <> S.MANUFACTURER
        OR T.CATEGORY             <> S.CATEGORY
        OR NVL(T.WEIGHT_KG,-1)    <> NVL(S.WEIGHT_KG,-1)
        OR T.UNIT_PRICE_USD       <> S.UNIT_PRICE_USD
        OR T.CERTIFICATION_STATUS <> S.CERTIFICATION_STATUS
        OR T.LEAD_TIME_DAYS       <> S.LEAD_TIME_DAYS
        OR T.PART_STATUS          <> S.PART_STATUS
        OR NVL(T.LIFECYCLE_STATUS,'~') <> NVL(S.LIFECYCLE_STATUS,'~')                             -- [DELTA] AC-005
        OR T.RISK_SCORE           <> S.RISK_SCORE
    ) THEN UPDATE SET
        T.PART_NAME            = S.PART_NAME,
        T.MANUFACTURER         = S.MANUFACTURER,
        T.CATEGORY             = S.CATEGORY,
        T.WEIGHT_KG            = S.WEIGHT_KG,
        T.UNIT_PRICE_USD       = S.UNIT_PRICE_USD,
        T.CERTIFICATION_STATUS = S.CERTIFICATION_STATUS,
        T.LEAD_TIME_DAYS       = S.LEAD_TIME_DAYS,
        T.PART_STATUS          = S.PART_STATUS,
        T.LIFECYCLE_STATUS     = S.LIFECYCLE_STATUS,                                               -- [DELTA] AC-005
        T.INSTALLATION_DATE    = S.INSTALLATION_DATE,
        T.UPDATED_AT           = S.UPDATED_AT,
        T.RISK_SCORE           = S.RISK_SCORE,
        T.LAST_UPDATED_TS      = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER, PART_NAME, MANUFACTURER, CATEGORY, WEIGHT_KG,
        UNIT_PRICE_USD, CERTIFICATION_STATUS, LEAD_TIME_DAYS, PART_STATUS,
        LIFECYCLE_STATUS, INSTALLATION_DATE, UPDATED_AT, RISK_SCORE, LAST_UPDATED_TS  -- [DELTA] AC-005
    ) VALUES (
        S.PART_NUMBER, S.PART_NAME, S.MANUFACTURER, S.CATEGORY, S.WEIGHT_KG,
        S.UNIT_PRICE_USD, S.CERTIFICATION_STATUS, S.LEAD_TIME_DAYS, S.PART_STATUS,
        S.LIFECYCLE_STATUS, S.INSTALLATION_DATE, S.UPDATED_AT, S.RISK_SCORE, CURRENT_TIMESTAMP()
    );

    v_tgt_update := SQLROWCOUNT;

    -- [DELTA] AC-007: Soft delete — mark as Decommissioned if absent from source
    UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET T
    SET    T.PART_STATUS     = 'Decommissioned',
           T.LAST_UPDATED_TS = CURRENT_TIMESTAMP()
    WHERE  T.PART_STATUS    <> 'Decommissioned'
      AND  NOT EXISTS (
               SELECT 1
               FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE S
               WHERE S.PART_NUMBER = T.PART_NUMBER
           );

    v_tgt_delete := SQLROWCOUNT;

    -- SECTION 5: Reconciliation

    v_end_ts := CURRENT_TIMESTAMP();

    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        PROCEDURE_NAME, RUN_START_TS, RUN_END_TS, SOURCE_COUNT,
        TARGET_UPSERT_COUNT, TARGET_DECOMMISSION_COUNT, WATERMARK_TS, STATUS, MESSAGE
    ) VALUES (
        :v_proc_name, :v_start_ts, :v_end_ts, :v_src_count,
        :v_tgt_update, :v_tgt_delete, CURRENT_TIMESTAMP(), :v_status, :v_message
    );

    RETURN OBJECT_CONSTRUCT(
        'status',        v_status,
        'source_count',  v_src_count,
        'upsert_count',  v_tgt_update,
        'decomm_count',  v_tgt_delete,
        'watermark_used',v_watermark_str,
        'run_start',     v_start_ts::VARCHAR,
        'run_end',       v_end_ts::VARCHAR
    )::VARCHAR;

-- SECTION 6: Error Handling
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;