/*=========================================================
Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
-- SECTION 1: Variables

    -- Watermark & run tracking
    v_watermark         TIMESTAMP_NTZ;
    v_new_watermark     TIMESTAMP_NTZ;
    v_run_id            VARCHAR;
    v_run_timestamp     TIMESTAMP_NTZ;

    -- Reconciliation counters
    v_source_count      INTEGER DEFAULT 0;
    v_inserted_count    INTEGER DEFAULT 0;
    v_updated_count     INTEGER DEFAULT 0;
    v_decommissioned    INTEGER DEFAULT 0;

    -- Status / error
    v_status            VARCHAR  DEFAULT 'SUCCESS';
    v_error_message     VARCHAR  DEFAULT NULL;

    -- Result
    v_result            VARCHAR;

BEGIN
    -- ----------------------------------------------------------------
    -- 0. Initialise run metadata
    -- ----------------------------------------------------------------
    v_run_id        := GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1.UNIQUE_ID()::VARCHAR;
    v_run_timestamp := CURRENT_TIMESTAMP::TIMESTAMP_NTZ;

    -- ----------------------------------------------------------------
    -- 1. Resolve watermark
    --    The MAX(NEW_WATERMARK) -- SECTION 2: Source Processing
from previous successful runs is used.
    --    NULL => first run => full load.
    -- ----------------------------------------------------------------
    SELECT -- SECTION 3: Data Validation
COALESCE(MAX(NEW_WATERMARK), '1900-01-01 00:00:00'::TIMESTAMP_NTZ)
      INTO v_watermark
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
     WHERE STATUS = 'SUCCESS';

    -- ----------------------------------------------------------------
    -- 2. Stage incremental + deduplicated source records
    --    • Only rows where UPDATED_AT > watermark
    --    • Deduplicate by PART_NUMBER, keeping latest UPDATED_AT
    --    • MANUFACTURER uppercased
    --    • WEIGHT_KG nullified when <= 0
    --    • RISK_SCORE derived:
    --        LEAD_TIME_DAYS > 90  AND LIFECYCLE_STATUS = 'END_OF_LIFE'  => 'HIGH'
    --        LEAD_TIME_DAYS > 60  OR  LIFECYCLE_STATUS = 'PHASE_OUT'    => 'MEDIUM'
    --        otherwise                                                   => 'LOW'
    -- ----------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_STAGED AS
    WITH RANKED AS (
        SELECT
            PART_NUMBER,
            UPPER(MANUFACTURER)                                         AS MANUFACTURER,
            CERTIFICATION_STATUS,
            INSTALLATION_DATE,
            LEAD_TIME_DAYS,
            LIFECYCLE_STATUS,
            STATUS,
            UNIT_PRICE_USD,
            UPDATED_AT,
            CASE WHEN WEIGHT_KG <= 0 THEN NULL ELSE WEIGHT_KG END      AS WEIGHT_KG,
            CASE
                WHEN LEAD_TIME_DAYS > 90
                 AND LIFECYCLE_STATUS = 'END_OF_LIFE'                   THEN 'HIGH'
                WHEN LEAD_TIME_DAYS > 60
                  OR LIFECYCLE_STATUS = 'PHASE_OUT'                     THEN 'MEDIUM'
                ELSE                                                         'LOW'
            END                                                         AS RISK_SCORE,
            ROW_NUMBER() OVER (
                PARTITION BY PART_NUMBER
                ORDER BY UPDATED_AT DESC
            )                                                           AS RN
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
        WHERE UPDATED_AT > v_watermark
          AND PART_NUMBER IS NOT NULL
    )
    SELECT
        PART_NUMBER,
        MANUFACTURER,
        CERTIFICATION_STATUS,
        INSTALLATION_DATE,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        STATUS,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WEIGHT_KG,
        RISK_SCORE
    FROM RANKED
    WHERE RN = 1;

    -- ----------------------------------------------------------------
    -- 3. Capture source count
    -- ----------------------------------------------------------------
    SELECT COUNT(*)
      INTO v_source_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_STAGED;

    -- ----------------------------------------------------------------
    -- 4. SCD Type 1 -- SECTION 4: Merge Logic
MERGE into target
    -- ----------------------------------------------------------------
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS TGT
    USING GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_STAGED       AS SRC
       ON TGT.PART_NUMBER = SRC.PART_NUMBER

    -- UPDATE existing records (SCD1 — overwrite all non-key attributes)
    WHEN MATCHED THEN UPDATE SET
        TGT.MANUFACTURER         = SRC.MANUFACTURER,
        TGT.CERTIFICATION_STATUS = SRC.CERTIFICATION_STATUS,
        TGT.INSTALLATION_DATE    = SRC.INSTALLATION_DATE,
        TGT.LEAD_TIME_DAYS       = SRC.LEAD_TIME_DAYS,
        TGT.LIFECYCLE_STATUS     = SRC.LIFECYCLE_STATUS,
        TGT.STATUS               = SRC.STATUS,
        TGT.UNIT_PRICE_USD       = SRC.UNIT_PRICE_USD,
        TGT.UPDATED_AT           = SRC.UPDATED_AT,
        TGT.WEIGHT_KG            = SRC.WEIGHT_KG,
        TGT.RISK_SCORE           = SRC.RISK_SCORE,
        TGT.DW_UPDATE_TIMESTAMP  = v_run_timestamp

    -- INSERT new records
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER,
        MANUFACTURER,
        CERTIFICATION_STATUS,
        INSTALLATION_DATE,
        LEAD_TIME_DAYS,
        LIFECYCLE_STATUS,
        STATUS,
        UNIT_PRICE_USD,
        UPDATED_AT,
        WEIGHT_KG,
        RISK_SCORE,
        DW_INSERT_TIMESTAMP,
        DW_UPDATE_TIMESTAMP
    ) VALUES (
        SRC.PART_NUMBER,
        SRC.MANUFACTURER,
        SRC.CERTIFICATION_STATUS,
        SRC.INSTALLATION_DATE,
        SRC.LEAD_TIME_DAYS,
        SRC.LIFECYCLE_STATUS,
        SRC.STATUS,
        SRC.UNIT_PRICE_USD,
        SRC.UPDATED_AT,
        SRC.WEIGHT_KG,
        SRC.RISK_SCORE,
        v_run_timestamp,
        v_run_timestamp
    );

    -- ----------------------------------------------------------------
    -- 5. Derive inserted / updated counts from MERGE result
    --    Snowflake exposes these via RESULT_SCAN on the last DML.
    -- ----------------------------------------------------------------
    LET merge_result RESULTSET := (
        SELECT
            "number of rows inserted" AS INS_CNT,
            "number of rows updated"  AS UPD_CNT
        FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
    );

    FOR rec IN merge_result DO
        v_inserted_count := rec.INS_CNT;
        v_updated_count  := rec.UPD_CNT;
    END FOR;

    -- ----------------------------------------------------------------
    -- 6. Decommission logic
    --    Mark target rows as 'DECOMMISSIONED' where the part exists in
    --    target but has been removed / set inactive in the full source
    --    (STATUS = 'INACTIVE' arriving in the incremental window).
    -- ----------------------------------------------------------------
    UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS TGT
       SET TGT.STATUS              = 'DECOMMISSIONED',
           TGT.LIFECYCLE_STATUS    = 'END_OF_LIFE',
           TGT.DW_UPDATE_TIMESTAMP = v_run_timestamp
    WHERE TGT.PART_NUMBER IN (
            SELECT PART_NUMBER
              FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_STAGED
             WHERE STATUS = 'INACTIVE'
          )
      AND TGT.STATUS <> 'DECOMMISSIONED';

    SELECT COUNT(*)
      INTO v_decommissioned
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
     WHERE STATUS              = 'DECOMMISSIONED'
       AND DW_UPDATE_TIMESTAMP = v_run_timestamp;

    -- ----------------------------------------------------------------
    -- 7. Compute new watermark = MAX(UPDATED_AT) processed this run
    -- ----------------------------------------------------------------
    SELECT COALESCE(MAX(UPDATED_AT), v_watermark)
      INTO v_new_watermark
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TEMP_AEROSPACE_STAGED;

    -- ----------------------------------------------------------------
    -- 8. Write reconciliation log — SUCCESS path
    -- ----------------------------------------------------------------
    -- SECTION 5: Reconciliation
INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        RUN_ID,
        RUN_TIMESTAMP,
        WATERMARK_USED,
        NEW_WATERMARK,
        SOURCE_COUNT,
        INSERTED_COUNT,
        UPDATED_COUNT,
        DECOMMISSIONED_COUNT,
        STATUS,
        ERROR_MESSAGE
    ) VALUES (
        v_run_id,
        v_run_timestamp,
        v_watermark,
        v_new_watermark,
        v_source_count,
        v_inserted_count,
        v_updated_count,
        v_decommissioned,
        v_status,
        v_error_message
    );

    -- ----------------------------------------------------------------
    -- 9. Build and return success result
    -- ----------------------------------------------------------------
    v_result := OBJECT_CONSTRUCT(
        'status',               v_status,
        'run_id',               v_run_id,
        'run_timestamp',        v_run_timestamp::VARCHAR,
        'watermark_used',       v_watermark::VARCHAR,
        'new_watermark',        v_new_watermark::VARCHAR,
        'source_count',         v_source_count,
        'inserted_count',       v_inserted_count,
        'updated_count',        v_updated_count,
        'decommissioned_count', v_decommissioned
    )::VARCHAR;

    RETURN v_result;

-- SECTION 6: Error Handling
EXCEPTION
    WHEN OTHER THEN

        v_status        := 'FAILED';
        v_error_message := SQLERRM;

        -- Attempt to log the failure — wrapped in its own block so a
        -- secondary failure does not suppress the original error message.
        BEGIN
            INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
                RUN_ID,
                RUN_TIMESTAMP,
                WATERMARK_USED,
                NEW_WATERMARK,
                SOURCE_COUNT,
                INSERTED_COUNT,
                UPDATED_COUNT,
                DECOMMISSIONED_COUNT,
                STATUS,
                ERROR_MESSAGE
            ) VALUES (
                v_run_id,
                v_run_timestamp,
                v_watermark,
                NULL,
                v_source_count,
                0,
                0,
                0,
                v_status,
                v_error_message
            );
        EXCEPTION
            WHEN OTHER THEN
                NULL;   -- Suppress secondary logging error; surface original below
        END;

        RETURN OBJECT_CONSTRUCT(
            'error',       v_error_message,
            'run_id',      v_run_id,
            'status',      v_status
        )::VARCHAR;

END;
$$;