/*=========================================================
Object Name : TASK_SP_AEROSPACE_PARTS_PIPELINE
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_SP_AEROSPACE_PARTS_PIPELINE
  WAREHOUSE = W_CAPG_APAC_IND_DEMO_IDEA_REFACTOR_SOL_XS
  SCHEDULE = 'USING CRON 0 05 * * * UTC'
AS
  CALL GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_AEROSPACE_PARTS_PIPELINE();